// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: common/v1/employee.proto

package v1

import (
	context "context"
	reflect "reflect"
	sync "sync"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 员工信息公共数据结构
type EmployeeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserName     string                 `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`           // 员工姓名
	WorkNumber   string                 `protobuf:"bytes,3,opt,name=WorkNumber,proto3" json:"WorkNumber,omitempty"`       // 员工工号
	Sex          int32                  `protobuf:"varint,4,opt,name=Sex,proto3" json:"Sex,omitempty"`                    // 性别（0：未知 1：男  2：女）
	Phone        string                 `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`                 // 手机号码
	Email        string                 `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`                 // 邮箱号码
	DepartId     int32                  `protobuf:"varint,7,opt,name=DepartId,proto3" json:"DepartId,omitempty"`          // 部门ID
	JobLevel     int32                  `protobuf:"varint,8,opt,name=JobLevel,proto3" json:"JobLevel,omitempty"`          // 职级
	JobId        int32                  `protobuf:"varint,9,opt,name=JobId,proto3" json:"JobId,omitempty"`                // 岗位信息
	InstructorId int32                  `protobuf:"varint,10,opt,name=InstructorId,proto3" json:"InstructorId,omitempty"` // 指导老师
	Status       int32                  `protobuf:"varint,11,opt,name=Status,proto3" json:"Status,omitempty"`             // 在职状态（1：在职 2：试用期 3：实习期 4：已离职）
	Remark       string                 `protobuf:"bytes,12,opt,name=Remark,proto3" json:"Remark,omitempty"`              // 预留备注信息
	CreateTime   *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`      // 数据新增时间
	UpdateTime   *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`      // 最后一次更新数据时间
}

func (x *EmployeeInfo) Reset() {
	*x = EmployeeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_employee_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmployeeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeInfo) ProtoMessage() {}

func (x *EmployeeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_employee_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeInfo.ProtoReflect.Descriptor instead.
func (*EmployeeInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_employee_proto_rawDescGZIP(), []int{0}
}

func (x *EmployeeInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EmployeeInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *EmployeeInfo) GetWorkNumber() string {
	if x != nil {
		return x.WorkNumber
	}
	return ""
}

func (x *EmployeeInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *EmployeeInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *EmployeeInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmployeeInfo) GetDepartId() int32 {
	if x != nil {
		return x.DepartId
	}
	return 0
}

func (x *EmployeeInfo) GetJobLevel() int32 {
	if x != nil {
		return x.JobLevel
	}
	return 0
}

func (x *EmployeeInfo) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *EmployeeInfo) GetInstructorId() int32 {
	if x != nil {
		return x.InstructorId
	}
	return 0
}

func (x *EmployeeInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *EmployeeInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *EmployeeInfo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *EmployeeInfo) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// 创建数据接口输入数据结构
type CreateEmployeeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remark       string `protobuf:"bytes,1,opt,name=Remark,proto3" json:"Remark,omitempty"`
	UserName     string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`           // 员工姓名
	WorkNumber   string `protobuf:"bytes,3,opt,name=WorkNumber,proto3" json:"WorkNumber,omitempty"`       // 员工工号
	Sex          int32  `protobuf:"varint,4,opt,name=Sex,proto3" json:"Sex,omitempty"`                    // 性别（0：未知 1：男  2：女）
	Phone        string `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`                 // 手机号码
	Email        string `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`                 // 邮箱号码
	DepartId     int32  `protobuf:"varint,7,opt,name=DepartId,proto3" json:"DepartId,omitempty"`          // 部门ID
	JobLevel     int32  `protobuf:"varint,8,opt,name=JobLevel,proto3" json:"JobLevel,omitempty"`          // 职级
	JobId        int32  `protobuf:"varint,9,opt,name=JobId,proto3" json:"JobId,omitempty"`                // 岗位信息
	InstructorId int32  `protobuf:"varint,10,opt,name=InstructorId,proto3" json:"InstructorId,omitempty"` // 指导老师
	Status       int32  `protobuf:"varint,11,opt,name=Status,proto3" json:"Status,omitempty"`             // 在职状态（1：在职 2：试用期 3：实习期 4：已离职）
}

func (x *CreateEmployeeReq) Reset() {
	*x = CreateEmployeeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_employee_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEmployeeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeReq) ProtoMessage() {}

func (x *CreateEmployeeReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_employee_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeReq.ProtoReflect.Descriptor instead.
func (*CreateEmployeeReq) Descriptor() ([]byte, []int) {
	return file_common_v1_employee_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEmployeeReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CreateEmployeeReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateEmployeeReq) GetWorkNumber() string {
	if x != nil {
		return x.WorkNumber
	}
	return ""
}

func (x *CreateEmployeeReq) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *CreateEmployeeReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateEmployeeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateEmployeeReq) GetDepartId() int32 {
	if x != nil {
		return x.DepartId
	}
	return 0
}

func (x *CreateEmployeeReq) GetJobLevel() int32 {
	if x != nil {
		return x.JobLevel
	}
	return 0
}

func (x *CreateEmployeeReq) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *CreateEmployeeReq) GetInstructorId() int32 {
	if x != nil {
		return x.InstructorId
	}
	return 0
}

func (x *CreateEmployeeReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 创建数据接口输出数据结构
type CreateEmployeeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Employee *EmployeeInfo `protobuf:"bytes,1,opt,name=Employee,proto3" json:"Employee,omitempty"`
}

func (x *CreateEmployeeRes) Reset() {
	*x = CreateEmployeeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_employee_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEmployeeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeRes) ProtoMessage() {}

func (x *CreateEmployeeRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_employee_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeRes.ProtoReflect.Descriptor instead.
func (*CreateEmployeeRes) Descriptor() ([]byte, []int) {
	return file_common_v1_employee_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEmployeeRes) GetEmployee() *EmployeeInfo {
	if x != nil {
		return x.Employee
	}
	return nil
}

// 获取详情接口输入数据结构
type GetOneEmployeeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                // v: required
	UserName   string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`     // 员工姓名
	WorkNumber string `protobuf:"bytes,3,opt,name=WorkNumber,proto3" json:"WorkNumber,omitempty"` // 员工工号
	Phone      string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`           // 手机号码
	Email      string `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`           // 邮箱号码
}

func (x *GetOneEmployeeReq) Reset() {
	*x = GetOneEmployeeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_employee_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneEmployeeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneEmployeeReq) ProtoMessage() {}

func (x *GetOneEmployeeReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_employee_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneEmployeeReq.ProtoReflect.Descriptor instead.
func (*GetOneEmployeeReq) Descriptor() ([]byte, []int) {
	return file_common_v1_employee_proto_rawDescGZIP(), []int{3}
}

func (x *GetOneEmployeeReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOneEmployeeReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetOneEmployeeReq) GetWorkNumber() string {
	if x != nil {
		return x.WorkNumber
	}
	return ""
}

func (x *GetOneEmployeeReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetOneEmployeeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// 获取详情接口输出数据结构
type GetOneEmployeeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Employee *EmployeeInfo `protobuf:"bytes,1,opt,name=Employee,proto3" json:"Employee,omitempty"`
}

func (x *GetOneEmployeeRes) Reset() {
	*x = GetOneEmployeeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_employee_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneEmployeeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneEmployeeRes) ProtoMessage() {}

func (x *GetOneEmployeeRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_employee_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneEmployeeRes.ProtoReflect.Descriptor instead.
func (*GetOneEmployeeRes) Descriptor() ([]byte, []int) {
	return file_common_v1_employee_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneEmployeeRes) GetEmployee() *EmployeeInfo {
	if x != nil {
		return x.Employee
	}
	return nil
}

// 部门列表接口输入数据结构
type GetListEmployeeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32         `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Size     int32         `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Employee *EmployeeInfo `protobuf:"bytes,3,opt,name=Employee,proto3" json:"Employee,omitempty"`
}

func (x *GetListEmployeeReq) Reset() {
	*x = GetListEmployeeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_employee_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListEmployeeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListEmployeeReq) ProtoMessage() {}

func (x *GetListEmployeeReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_employee_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListEmployeeReq.ProtoReflect.Descriptor instead.
func (*GetListEmployeeReq) Descriptor() ([]byte, []int) {
	return file_common_v1_employee_proto_rawDescGZIP(), []int{5}
}

func (x *GetListEmployeeReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListEmployeeReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListEmployeeReq) GetEmployee() *EmployeeInfo {
	if x != nil {
		return x.Employee
	}
	return nil
}

// 部门列表接口输出数据结构
type GetListEmployeeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32         `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Size int32         `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Data *EmployeeInfo `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetListEmployeeRes) Reset() {
	*x = GetListEmployeeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_employee_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListEmployeeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListEmployeeRes) ProtoMessage() {}

func (x *GetListEmployeeRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_employee_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListEmployeeRes.ProtoReflect.Descriptor instead.
func (*GetListEmployeeRes) Descriptor() ([]byte, []int) {
	return file_common_v1_employee_proto_rawDescGZIP(), []int{6}
}

func (x *GetListEmployeeRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListEmployeeRes) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListEmployeeRes) GetData() *EmployeeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 修改数据接口输入数据结构
type ModifyEmployeeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remark       string `protobuf:"bytes,1,opt,name=Remark,proto3" json:"Remark,omitempty"`
	UserName     string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`           // 员工姓名
	WorkNumber   string `protobuf:"bytes,3,opt,name=WorkNumber,proto3" json:"WorkNumber,omitempty"`       // 员工工号
	Sex          int32  `protobuf:"varint,4,opt,name=Sex,proto3" json:"Sex,omitempty"`                    // 性别（0：未知 1：男  2：女）
	Phone        string `protobuf:"bytes,5,opt,name=Phone,proto3" json:"Phone,omitempty"`                 // 手机号码
	Email        string `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`                 // 邮箱号码
	DepartId     int32  `protobuf:"varint,7,opt,name=DepartId,proto3" json:"DepartId,omitempty"`          // 部门ID
	JobLevel     int32  `protobuf:"varint,8,opt,name=JobLevel,proto3" json:"JobLevel,omitempty"`          // 职级
	JobId        int32  `protobuf:"varint,9,opt,name=JobId,proto3" json:"JobId,omitempty"`                // 岗位信息
	InstructorId int32  `protobuf:"varint,10,opt,name=InstructorId,proto3" json:"InstructorId,omitempty"` // 指导老师
	Status       int32  `protobuf:"varint,11,opt,name=Status,proto3" json:"Status,omitempty"`             // 在职状态（1：在职 2：试用期 3：实习期 4：已离职）
	Id           int32  `protobuf:"varint,12,opt,name=Id,proto3" json:"Id,omitempty"`                     // v: required
}

func (x *ModifyEmployeeReq) Reset() {
	*x = ModifyEmployeeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_employee_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyEmployeeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyEmployeeReq) ProtoMessage() {}

func (x *ModifyEmployeeReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_employee_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyEmployeeReq.ProtoReflect.Descriptor instead.
func (*ModifyEmployeeReq) Descriptor() ([]byte, []int) {
	return file_common_v1_employee_proto_rawDescGZIP(), []int{7}
}

func (x *ModifyEmployeeReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ModifyEmployeeReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ModifyEmployeeReq) GetWorkNumber() string {
	if x != nil {
		return x.WorkNumber
	}
	return ""
}

func (x *ModifyEmployeeReq) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *ModifyEmployeeReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ModifyEmployeeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ModifyEmployeeReq) GetDepartId() int32 {
	if x != nil {
		return x.DepartId
	}
	return 0
}

func (x *ModifyEmployeeReq) GetJobLevel() int32 {
	if x != nil {
		return x.JobLevel
	}
	return 0
}

func (x *ModifyEmployeeReq) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *ModifyEmployeeReq) GetInstructorId() int32 {
	if x != nil {
		return x.InstructorId
	}
	return 0
}

func (x *ModifyEmployeeReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ModifyEmployeeReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 修改数据接口输出数据结构
type ModifyEmployeeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Employee *EmployeeInfo `protobuf:"bytes,3,opt,name=Employee,proto3" json:"Employee,omitempty"`
}

func (x *ModifyEmployeeRes) Reset() {
	*x = ModifyEmployeeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_employee_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyEmployeeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyEmployeeRes) ProtoMessage() {}

func (x *ModifyEmployeeRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_employee_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyEmployeeRes.ProtoReflect.Descriptor instead.
func (*ModifyEmployeeRes) Descriptor() ([]byte, []int) {
	return file_common_v1_employee_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyEmployeeRes) GetEmployee() *EmployeeInfo {
	if x != nil {
		return x.Employee
	}
	return nil
}

// 删除数据接口输入数据结构
type DeleteEmployeeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"` // v: required
}

func (x *DeleteEmployeeReq) Reset() {
	*x = DeleteEmployeeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_employee_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmployeeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeReq) ProtoMessage() {}

func (x *DeleteEmployeeReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_employee_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeReq.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeReq) Descriptor() ([]byte, []int) {
	return file_common_v1_employee_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteEmployeeReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除数据接口输出数据结构
type DeleteEmployeeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"` // v: required
	Msg       string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`              // v: required
}

func (x *DeleteEmployeeRes) Reset() {
	*x = DeleteEmployeeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_employee_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEmployeeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeRes) ProtoMessage() {}

func (x *DeleteEmployeeRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_employee_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeRes.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeRes) Descriptor() ([]byte, []int) {
	return file_common_v1_employee_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteEmployeeRes) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *DeleteEmployeeRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_common_v1_employee_proto protoreflect.FileDescriptor

var file_common_v1_employee_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xb2, 0x03, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x53,
	0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4a, 0x6f,
	0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4a, 0x6f,
	0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x12, 0x3a, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xaf, 0x02, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x53, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49,
	0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x45, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x12,
	0x30, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f,
	0x79, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x22, 0x8b, 0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x57, 0x6f, 0x72, 0x6b, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22,
	0x45, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x22, 0x6e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x22, 0x66, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0xbf,
	0x02, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x6b,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x57, 0x6f,
	0x72, 0x6b, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x65, 0x78, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x53, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x14,
	0x0a, 0x05, 0x4a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4a,
	0x6f, 0x62, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x49, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64,
	0x22, 0x45, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73,
	0x67, 0x32, 0xd7, 0x02, 0x0a, 0x08, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x40,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x40, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x6e, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x43, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79,
	0x65, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x45, 0x6d, 0x70, 0x6c,
	0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x06, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6d,
	0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6a, 0x31, 0x35, 0x37, 0x30,
	0x36, 0x39, 0x33, 0x36, 0x35, 0x39, 0x2f, 0x67, 0x66, 0x63, 0x71, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6d, 0x70,
	0x6c, 0x6f, 0x79, 0x65, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_v1_employee_proto_rawDescOnce sync.Once
	file_common_v1_employee_proto_rawDescData = file_common_v1_employee_proto_rawDesc
)

func file_common_v1_employee_proto_rawDescGZIP() []byte {
	file_common_v1_employee_proto_rawDescOnce.Do(func() {
		file_common_v1_employee_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_v1_employee_proto_rawDescData)
	})
	return file_common_v1_employee_proto_rawDescData
}

var file_common_v1_employee_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_common_v1_employee_proto_goTypes = []interface{}{
	(*EmployeeInfo)(nil),          // 0: common.EmployeeInfo
	(*CreateEmployeeReq)(nil),     // 1: common.CreateEmployeeReq
	(*CreateEmployeeRes)(nil),     // 2: common.CreateEmployeeRes
	(*GetOneEmployeeReq)(nil),     // 3: common.GetOneEmployeeReq
	(*GetOneEmployeeRes)(nil),     // 4: common.GetOneEmployeeRes
	(*GetListEmployeeReq)(nil),    // 5: common.GetListEmployeeReq
	(*GetListEmployeeRes)(nil),    // 6: common.GetListEmployeeRes
	(*ModifyEmployeeReq)(nil),     // 7: common.ModifyEmployeeReq
	(*ModifyEmployeeRes)(nil),     // 8: common.ModifyEmployeeRes
	(*DeleteEmployeeReq)(nil),     // 9: common.DeleteEmployeeReq
	(*DeleteEmployeeRes)(nil),     // 10: common.DeleteEmployeeRes
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_common_v1_employee_proto_depIdxs = []int32{
	11, // 0: common.EmployeeInfo.CreateTime:type_name -> google.protobuf.Timestamp
	11, // 1: common.EmployeeInfo.UpdateTime:type_name -> google.protobuf.Timestamp
	0,  // 2: common.CreateEmployeeRes.Employee:type_name -> common.EmployeeInfo
	0,  // 3: common.GetOneEmployeeRes.Employee:type_name -> common.EmployeeInfo
	0,  // 4: common.GetListEmployeeReq.Employee:type_name -> common.EmployeeInfo
	0,  // 5: common.GetListEmployeeRes.Data:type_name -> common.EmployeeInfo
	0,  // 6: common.ModifyEmployeeRes.Employee:type_name -> common.EmployeeInfo
	1,  // 7: common.Employee.Create:input_type -> common.CreateEmployeeReq
	3,  // 8: common.Employee.GetOne:input_type -> common.GetOneEmployeeReq
	5,  // 9: common.Employee.GetList:input_type -> common.GetListEmployeeReq
	7,  // 10: common.Employee.Modify:input_type -> common.ModifyEmployeeReq
	9,  // 11: common.Employee.Delete:input_type -> common.DeleteEmployeeReq
	2,  // 12: common.Employee.Create:output_type -> common.CreateEmployeeRes
	4,  // 13: common.Employee.GetOne:output_type -> common.GetOneEmployeeRes
	6,  // 14: common.Employee.GetList:output_type -> common.GetListEmployeeRes
	8,  // 15: common.Employee.Modify:output_type -> common.ModifyEmployeeRes
	10, // 16: common.Employee.Delete:output_type -> common.DeleteEmployeeRes
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_common_v1_employee_proto_init() }
func file_common_v1_employee_proto_init() {
	if File_common_v1_employee_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_v1_employee_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmployeeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_employee_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEmployeeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_employee_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEmployeeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_employee_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneEmployeeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_employee_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneEmployeeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_employee_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListEmployeeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_employee_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListEmployeeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_employee_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyEmployeeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_employee_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyEmployeeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_employee_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmployeeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_employee_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEmployeeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_v1_employee_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_v1_employee_proto_goTypes,
		DependencyIndexes: file_common_v1_employee_proto_depIdxs,
		MessageInfos:      file_common_v1_employee_proto_msgTypes,
	}.Build()
	File_common_v1_employee_proto = out.File
	file_common_v1_employee_proto_rawDesc = nil
	file_common_v1_employee_proto_goTypes = nil
	file_common_v1_employee_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EmployeeClient is the client API for Employee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeClient interface {
	Create(ctx context.Context, in *CreateEmployeeReq, opts ...grpc.CallOption) (*CreateEmployeeRes, error)
	GetOne(ctx context.Context, in *GetOneEmployeeReq, opts ...grpc.CallOption) (*GetOneEmployeeRes, error)
	GetList(ctx context.Context, in *GetListEmployeeReq, opts ...grpc.CallOption) (*GetListEmployeeRes, error)
	Modify(ctx context.Context, in *ModifyEmployeeReq, opts ...grpc.CallOption) (*ModifyEmployeeRes, error)
	Delete(ctx context.Context, in *DeleteEmployeeReq, opts ...grpc.CallOption) (*DeleteEmployeeRes, error)
}

type employeeClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeClient(cc grpc.ClientConnInterface) EmployeeClient {
	return &employeeClient{cc}
}

func (c *employeeClient) Create(ctx context.Context, in *CreateEmployeeReq, opts ...grpc.CallOption) (*CreateEmployeeRes, error) {
	out := new(CreateEmployeeRes)
	err := c.cc.Invoke(ctx, "/common.Employee/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) GetOne(ctx context.Context, in *GetOneEmployeeReq, opts ...grpc.CallOption) (*GetOneEmployeeRes, error) {
	out := new(GetOneEmployeeRes)
	err := c.cc.Invoke(ctx, "/common.Employee/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) GetList(ctx context.Context, in *GetListEmployeeReq, opts ...grpc.CallOption) (*GetListEmployeeRes, error) {
	out := new(GetListEmployeeRes)
	err := c.cc.Invoke(ctx, "/common.Employee/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) Modify(ctx context.Context, in *ModifyEmployeeReq, opts ...grpc.CallOption) (*ModifyEmployeeRes, error) {
	out := new(ModifyEmployeeRes)
	err := c.cc.Invoke(ctx, "/common.Employee/Modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) Delete(ctx context.Context, in *DeleteEmployeeReq, opts ...grpc.CallOption) (*DeleteEmployeeRes, error) {
	out := new(DeleteEmployeeRes)
	err := c.cc.Invoke(ctx, "/common.Employee/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServer is the server API for Employee service.
type EmployeeServer interface {
	Create(context.Context, *CreateEmployeeReq) (*CreateEmployeeRes, error)
	GetOne(context.Context, *GetOneEmployeeReq) (*GetOneEmployeeRes, error)
	GetList(context.Context, *GetListEmployeeReq) (*GetListEmployeeRes, error)
	Modify(context.Context, *ModifyEmployeeReq) (*ModifyEmployeeRes, error)
	Delete(context.Context, *DeleteEmployeeReq) (*DeleteEmployeeRes, error)
}

// UnimplementedEmployeeServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServer struct {
}

func (*UnimplementedEmployeeServer) Create(context.Context, *CreateEmployeeReq) (*CreateEmployeeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedEmployeeServer) GetOne(context.Context, *GetOneEmployeeReq) (*GetOneEmployeeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (*UnimplementedEmployeeServer) GetList(context.Context, *GetListEmployeeReq) (*GetListEmployeeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedEmployeeServer) Modify(context.Context, *ModifyEmployeeReq) (*ModifyEmployeeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (*UnimplementedEmployeeServer) Delete(context.Context, *DeleteEmployeeReq) (*DeleteEmployeeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterEmployeeServer(s *grpc.Server, srv EmployeeServer) {
	s.RegisterService(&_Employee_serviceDesc, srv)
}

func _Employee_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmployeeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Employee/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).Create(ctx, req.(*CreateEmployeeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneEmployeeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Employee/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).GetOne(ctx, req.(*GetOneEmployeeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListEmployeeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Employee/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).GetList(ctx, req.(*GetListEmployeeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyEmployeeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Employee/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).Modify(ctx, req.(*ModifyEmployeeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmployeeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Employee/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).Delete(ctx, req.(*DeleteEmployeeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Employee_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.Employee",
	HandlerType: (*EmployeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Employee_Create_Handler,
		},
		{
			MethodName: "GetOne",
			Handler:    _Employee_GetOne_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _Employee_GetList_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _Employee_Modify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Employee_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/v1/employee.proto",
}
