// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: common/v1/job.proto

package v1

import (
	context "context"
	reflect "reflect"
	sync "sync"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 岗位信息公共数据结构
type JobInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`             // 岗位名称
	DepartId   int32                  `protobuf:"varint,3,opt,name=DepartId,proto3" json:"DepartId,omitempty"`    // 部门ID
	Remark     string                 `protobuf:"bytes,4,opt,name=Remark,proto3" json:"Remark,omitempty"`         // 预留备注信息
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"` // 数据新增时间
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"` // 最后一次更新数据时间
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *JobInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobInfo) GetDepartId() int32 {
	if x != nil {
		return x.DepartId
	}
	return 0
}

func (x *JobInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *JobInfo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *JobInfo) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

// 创建数据接口输入数据结构
type CreateJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DepartId int32  `protobuf:"varint,1,opt,name=DepartId,proto3" json:"DepartId,omitempty"` // v: required
	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`          // v: required
	Remark   string `protobuf:"bytes,3,opt,name=Remark,proto3" json:"Remark,omitempty"`      // v: required
}

func (x *CreateJobReq) Reset() {
	*x = CreateJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobReq) ProtoMessage() {}

func (x *CreateJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobReq.ProtoReflect.Descriptor instead.
func (*CreateJobReq) Descriptor() ([]byte, []int) {
	return file_common_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobReq) GetDepartId() int32 {
	if x != nil {
		return x.DepartId
	}
	return 0
}

func (x *CreateJobReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateJobReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 创建数据接口输出数据结构
type CreateJobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job *JobInfo `protobuf:"bytes,1,opt,name=Job,proto3" json:"Job,omitempty"`
}

func (x *CreateJobRes) Reset() {
	*x = CreateJobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRes) ProtoMessage() {}

func (x *CreateJobRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRes.ProtoReflect.Descriptor instead.
func (*CreateJobRes) Descriptor() ([]byte, []int) {
	return file_common_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJobRes) GetJob() *JobInfo {
	if x != nil {
		return x.Job
	}
	return nil
}

// 获取详情接口输入数据结构
type GetOneJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`     // v: required
	Name int32 `protobuf:"varint,2,opt,name=Name,proto3" json:"Name,omitempty"` // 岗位名称
}

func (x *GetOneJobReq) Reset() {
	*x = GetOneJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneJobReq) ProtoMessage() {}

func (x *GetOneJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneJobReq.ProtoReflect.Descriptor instead.
func (*GetOneJobReq) Descriptor() ([]byte, []int) {
	return file_common_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *GetOneJobReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOneJobReq) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

// 获取详情接口输出数据结构
type GetOneJobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job *JobInfo `protobuf:"bytes,1,opt,name=Job,proto3" json:"Job,omitempty"`
}

func (x *GetOneJobRes) Reset() {
	*x = GetOneJobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneJobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneJobRes) ProtoMessage() {}

func (x *GetOneJobRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneJobRes.ProtoReflect.Descriptor instead.
func (*GetOneJobRes) Descriptor() ([]byte, []int) {
	return file_common_v1_job_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneJobRes) GetJob() *JobInfo {
	if x != nil {
		return x.Job
	}
	return nil
}

// 部门列表接口输入数据结构
type GetListJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Size int32    `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Job  *JobInfo `protobuf:"bytes,3,opt,name=Job,proto3" json:"Job,omitempty"`
}

func (x *GetListJobReq) Reset() {
	*x = GetListJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListJobReq) ProtoMessage() {}

func (x *GetListJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListJobReq.ProtoReflect.Descriptor instead.
func (*GetListJobReq) Descriptor() ([]byte, []int) {
	return file_common_v1_job_proto_rawDescGZIP(), []int{5}
}

func (x *GetListJobReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListJobReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListJobReq) GetJob() *JobInfo {
	if x != nil {
		return x.Job
	}
	return nil
}

// 部门列表接口输出数据结构
type GetListJobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Size int32    `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	Data *JobInfo `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *GetListJobRes) Reset() {
	*x = GetListJobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListJobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListJobRes) ProtoMessage() {}

func (x *GetListJobRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListJobRes.ProtoReflect.Descriptor instead.
func (*GetListJobRes) Descriptor() ([]byte, []int) {
	return file_common_v1_job_proto_rawDescGZIP(), []int{6}
}

func (x *GetListJobRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListJobRes) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListJobRes) GetData() *JobInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 修改数据接口输入数据结构
type ModifyJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`             // v: required
	DepartId int32  `protobuf:"varint,2,opt,name=DepartId,proto3" json:"DepartId,omitempty"` // v: required
	Name     string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`          // v: required
	Remark   string `protobuf:"bytes,4,opt,name=Remark,proto3" json:"Remark,omitempty"`      // v: required
}

func (x *ModifyJobReq) Reset() {
	*x = ModifyJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyJobReq) ProtoMessage() {}

func (x *ModifyJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyJobReq.ProtoReflect.Descriptor instead.
func (*ModifyJobReq) Descriptor() ([]byte, []int) {
	return file_common_v1_job_proto_rawDescGZIP(), []int{7}
}

func (x *ModifyJobReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModifyJobReq) GetDepartId() int32 {
	if x != nil {
		return x.DepartId
	}
	return 0
}

func (x *ModifyJobReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModifyJobReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 修改数据接口输出数据结构
type ModifyJobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job *JobInfo `protobuf:"bytes,1,opt,name=Job,proto3" json:"Job,omitempty"`
}

func (x *ModifyJobRes) Reset() {
	*x = ModifyJobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyJobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyJobRes) ProtoMessage() {}

func (x *ModifyJobRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyJobRes.ProtoReflect.Descriptor instead.
func (*ModifyJobRes) Descriptor() ([]byte, []int) {
	return file_common_v1_job_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyJobRes) GetJob() *JobInfo {
	if x != nil {
		return x.Job
	}
	return nil
}

// 删除数据接口输入数据结构
type DeleteJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"` // v: required
}

func (x *DeleteJobReq) Reset() {
	*x = DeleteJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobReq) ProtoMessage() {}

func (x *DeleteJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobReq.ProtoReflect.Descriptor instead.
func (*DeleteJobReq) Descriptor() ([]byte, []int) {
	return file_common_v1_job_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteJobReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除数据接口输出数据结构
type DeleteJobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess,omitempty"` // v: required
	Msg       string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`              // v: required
}

func (x *DeleteJobRes) Reset() {
	*x = DeleteJobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteJobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobRes) ProtoMessage() {}

func (x *DeleteJobRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobRes.ProtoReflect.Descriptor instead.
func (*DeleteJobRes) Descriptor() ([]byte, []int) {
	return file_common_v1_job_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteJobRes) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *DeleteJobRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_common_v1_job_proto protoreflect.FileDescriptor

var file_common_v1_job_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd9,
	0x01, 0x0a, 0x07, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65,
	0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x12, 0x3a, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3a,
	0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x56, 0x0a, 0x0c, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65,
	0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x22, 0x31, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x12, 0x21, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x03, 0x4a, 0x6f, 0x62, 0x22, 0x32, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4a,
	0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x03, 0x4a, 0x6f, 0x62,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x4a, 0x6f, 0x62, 0x22, 0x5a, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x03, 0x4a, 0x6f, 0x62, 0x22, 0x5c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x23, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x66, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x31,
	0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x12, 0x21,
	0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x4a, 0x6f,
	0x62, 0x22, 0x1e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49,
	0x64, 0x22, 0x3e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73,
	0x67, 0x32, 0xa0, 0x02, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x36, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x36, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x14, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x71, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e,
	0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12, 0x14,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f,
	0x64, 0x69, 0x66, 0x79, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6c, 0x6a, 0x31, 0x35, 0x37, 0x30, 0x36, 0x39, 0x33, 0x36, 0x35, 0x39, 0x2f,
	0x67, 0x66, 0x63, 0x71, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_common_v1_job_proto_rawDescOnce sync.Once
	file_common_v1_job_proto_rawDescData = file_common_v1_job_proto_rawDesc
)

func file_common_v1_job_proto_rawDescGZIP() []byte {
	file_common_v1_job_proto_rawDescOnce.Do(func() {
		file_common_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_v1_job_proto_rawDescData)
	})
	return file_common_v1_job_proto_rawDescData
}

var file_common_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_common_v1_job_proto_goTypes = []interface{}{
	(*JobInfo)(nil),               // 0: common.JobInfo
	(*CreateJobReq)(nil),          // 1: common.CreateJobReq
	(*CreateJobRes)(nil),          // 2: common.CreateJobRes
	(*GetOneJobReq)(nil),          // 3: common.GetOneJobReq
	(*GetOneJobRes)(nil),          // 4: common.GetOneJobRes
	(*GetListJobReq)(nil),         // 5: common.GetListJobReq
	(*GetListJobRes)(nil),         // 6: common.GetListJobRes
	(*ModifyJobReq)(nil),          // 7: common.ModifyJobReq
	(*ModifyJobRes)(nil),          // 8: common.ModifyJobRes
	(*DeleteJobReq)(nil),          // 9: common.DeleteJobReq
	(*DeleteJobRes)(nil),          // 10: common.DeleteJobRes
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_common_v1_job_proto_depIdxs = []int32{
	11, // 0: common.JobInfo.CreateTime:type_name -> google.protobuf.Timestamp
	11, // 1: common.JobInfo.UpdateTime:type_name -> google.protobuf.Timestamp
	0,  // 2: common.CreateJobRes.Job:type_name -> common.JobInfo
	0,  // 3: common.GetOneJobRes.Job:type_name -> common.JobInfo
	0,  // 4: common.GetListJobReq.Job:type_name -> common.JobInfo
	0,  // 5: common.GetListJobRes.Data:type_name -> common.JobInfo
	0,  // 6: common.ModifyJobRes.Job:type_name -> common.JobInfo
	1,  // 7: common.Job.Create:input_type -> common.CreateJobReq
	3,  // 8: common.Job.GetOne:input_type -> common.GetOneJobReq
	5,  // 9: common.Job.GetList:input_type -> common.GetListJobReq
	7,  // 10: common.Job.Modify:input_type -> common.ModifyJobReq
	9,  // 11: common.Job.Delete:input_type -> common.DeleteJobReq
	2,  // 12: common.Job.Create:output_type -> common.CreateJobRes
	4,  // 13: common.Job.GetOne:output_type -> common.GetOneJobRes
	6,  // 14: common.Job.GetList:output_type -> common.GetListJobRes
	8,  // 15: common.Job.Modify:output_type -> common.ModifyJobRes
	10, // 16: common.Job.Delete:output_type -> common.DeleteJobRes
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_common_v1_job_proto_init() }
func file_common_v1_job_proto_init() {
	if File_common_v1_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_v1_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneJobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListJobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyJobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteJobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_v1_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_v1_job_proto_goTypes,
		DependencyIndexes: file_common_v1_job_proto_depIdxs,
		MessageInfos:      file_common_v1_job_proto_msgTypes,
	}.Build()
	File_common_v1_job_proto = out.File
	file_common_v1_job_proto_rawDesc = nil
	file_common_v1_job_proto_goTypes = nil
	file_common_v1_job_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JobClient is the client API for Job service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobClient interface {
	Create(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobRes, error)
	GetOne(ctx context.Context, in *GetOneJobReq, opts ...grpc.CallOption) (*GetOneJobRes, error)
	GetList(ctx context.Context, in *GetListJobReq, opts ...grpc.CallOption) (*GetListJobRes, error)
	Modify(ctx context.Context, in *ModifyJobReq, opts ...grpc.CallOption) (*ModifyJobRes, error)
	Delete(ctx context.Context, in *DeleteJobReq, opts ...grpc.CallOption) (*DeleteJobRes, error)
}

type jobClient struct {
	cc grpc.ClientConnInterface
}

func NewJobClient(cc grpc.ClientConnInterface) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) Create(ctx context.Context, in *CreateJobReq, opts ...grpc.CallOption) (*CreateJobRes, error) {
	out := new(CreateJobRes)
	err := c.cc.Invoke(ctx, "/common.Job/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetOne(ctx context.Context, in *GetOneJobReq, opts ...grpc.CallOption) (*GetOneJobRes, error) {
	out := new(GetOneJobRes)
	err := c.cc.Invoke(ctx, "/common.Job/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) GetList(ctx context.Context, in *GetListJobReq, opts ...grpc.CallOption) (*GetListJobRes, error) {
	out := new(GetListJobRes)
	err := c.cc.Invoke(ctx, "/common.Job/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) Modify(ctx context.Context, in *ModifyJobReq, opts ...grpc.CallOption) (*ModifyJobRes, error) {
	out := new(ModifyJobRes)
	err := c.cc.Invoke(ctx, "/common.Job/Modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobClient) Delete(ctx context.Context, in *DeleteJobReq, opts ...grpc.CallOption) (*DeleteJobRes, error) {
	out := new(DeleteJobRes)
	err := c.cc.Invoke(ctx, "/common.Job/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServer is the server API for Job service.
type JobServer interface {
	Create(context.Context, *CreateJobReq) (*CreateJobRes, error)
	GetOne(context.Context, *GetOneJobReq) (*GetOneJobRes, error)
	GetList(context.Context, *GetListJobReq) (*GetListJobRes, error)
	Modify(context.Context, *ModifyJobReq) (*ModifyJobRes, error)
	Delete(context.Context, *DeleteJobReq) (*DeleteJobRes, error)
}

// UnimplementedJobServer can be embedded to have forward compatible implementations.
type UnimplementedJobServer struct {
}

func (*UnimplementedJobServer) Create(context.Context, *CreateJobReq) (*CreateJobRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedJobServer) GetOne(context.Context, *GetOneJobReq) (*GetOneJobRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (*UnimplementedJobServer) GetList(context.Context, *GetListJobReq) (*GetListJobRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedJobServer) Modify(context.Context, *ModifyJobReq) (*ModifyJobRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (*UnimplementedJobServer) Delete(context.Context, *DeleteJobReq) (*DeleteJobRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterJobServer(s *grpc.Server, srv JobServer) {
	s.RegisterService(&_Job_serviceDesc, srv)
}

func _Job_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Job/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Create(ctx, req.(*CreateJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Job/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetOne(ctx, req.(*GetOneJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Job/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).GetList(ctx, req.(*GetListJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Job/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Modify(ctx, req.(*ModifyJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Job_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.Job/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Delete(ctx, req.(*DeleteJobReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Job_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Job_Create_Handler,
		},
		{
			MethodName: "GetOne",
			Handler:    _Job_GetOne_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _Job_GetList_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _Job_Modify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Job_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/v1/job.proto",
}
