// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: common/v1/job_level.proto

package v1

import (
	context "context"
	reflect "reflect"
	sync "sync"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderEnum int32

const (
	OrderEnum_random OrderEnum = 0 // 不排序，随机
	OrderEnum_desc   OrderEnum = 1 // 倒叙
	OrderEnum_asc    OrderEnum = 2 // 顺序
)

// Enum value maps for OrderEnum.
var (
	OrderEnum_name = map[int32]string{
		0: "random",
		1: "desc",
		2: "asc",
	}
	OrderEnum_value = map[string]int32{
		"random": 0,
		"desc":   1,
		"asc":    2,
	}
)

func (x OrderEnum) Enum() *OrderEnum {
	p := new(OrderEnum)
	*p = x
	return p
}

func (x OrderEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_job_level_proto_enumTypes[0].Descriptor()
}

func (OrderEnum) Type() protoreflect.EnumType {
	return &file_common_v1_job_level_proto_enumTypes[0]
}

func (x OrderEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderEnum.Descriptor instead.
func (OrderEnum) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{0}
}

// 公共数据结构
type JobLevelInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	Name       string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`             // 职级名称
	Remark     string `protobuf:"bytes,3,opt,name=Remark,proto3" json:"Remark"`         // 预留备注信息
	CreateTime string `protobuf:"bytes,4,opt,name=CreateTime,proto3" json:"CreateTime"` // 数据新增时间
	UpdateTime string `protobuf:"bytes,5,opt,name=UpdateTime,proto3" json:"UpdateTime"` // 最后一次更新数据时间
}

func (x *JobLevelInfo) Reset() {
	*x = JobLevelInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobLevelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLevelInfo) ProtoMessage() {}

func (x *JobLevelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLevelInfo.ProtoReflect.Descriptor instead.
func (*JobLevelInfo) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{0}
}

func (x *JobLevelInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JobLevelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobLevelInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *JobLevelInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *JobLevelInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

// 创建数据接口输入数据结构
type CreateJobLevelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name"` // v: required
	Remark string `protobuf:"bytes,2,opt,name=Remark,proto3" json:"Remark"`
}

func (x *CreateJobLevelReq) Reset() {
	*x = CreateJobLevelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJobLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobLevelReq) ProtoMessage() {}

func (x *CreateJobLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobLevelReq.ProtoReflect.Descriptor instead.
func (*CreateJobLevelReq) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{1}
}

func (x *CreateJobLevelReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateJobLevelReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 创建数据接口输出数据结构
type CreateJobLevelRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobLevel *JobLevelInfo `protobuf:"bytes,1,opt,name=JobLevel,proto3" json:"JobLevel"`
}

func (x *CreateJobLevelRes) Reset() {
	*x = CreateJobLevelRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateJobLevelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobLevelRes) ProtoMessage() {}

func (x *CreateJobLevelRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobLevelRes.ProtoReflect.Descriptor instead.
func (*CreateJobLevelRes) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{2}
}

func (x *CreateJobLevelRes) GetJobLevel() *JobLevelInfo {
	if x != nil {
		return x.JobLevel
	}
	return nil
}

// 获取详情接口输入数据结构
type GetOneJobLevelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`    // v: required
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"` // 职级名称
}

func (x *GetOneJobLevelReq) Reset() {
	*x = GetOneJobLevelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneJobLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneJobLevelReq) ProtoMessage() {}

func (x *GetOneJobLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneJobLevelReq.ProtoReflect.Descriptor instead.
func (*GetOneJobLevelReq) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{3}
}

func (x *GetOneJobLevelReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOneJobLevelReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 获取详情接口输出数据结构
type GetOneJobLevelRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobLevel *JobLevelInfo `protobuf:"bytes,1,opt,name=JobLevel,proto3" json:"JobLevel"`
}

func (x *GetOneJobLevelRes) Reset() {
	*x = GetOneJobLevelRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneJobLevelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneJobLevelRes) ProtoMessage() {}

func (x *GetOneJobLevelRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneJobLevelRes.ProtoReflect.Descriptor instead.
func (*GetOneJobLevelRes) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneJobLevelRes) GetJobLevel() *JobLevelInfo {
	if x != nil {
		return x.JobLevel
	}
	return nil
}

// 列表接口输入数据结构
type GetListJobLevelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32         `protobuf:"varint,1,opt,name=Page,proto3" json:"Page"`
	Size     int32         `protobuf:"varint,2,opt,name=Size,proto3" json:"Size"`
	JobLevel *JobLevelInfo `protobuf:"bytes,3,opt,name=JobLevel,proto3" json:"JobLevel"`
}

func (x *GetListJobLevelReq) Reset() {
	*x = GetListJobLevelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListJobLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListJobLevelReq) ProtoMessage() {}

func (x *GetListJobLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListJobLevelReq.ProtoReflect.Descriptor instead.
func (*GetListJobLevelReq) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{5}
}

func (x *GetListJobLevelReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListJobLevelReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListJobLevelReq) GetJobLevel() *JobLevelInfo {
	if x != nil {
		return x.JobLevel
	}
	return nil
}

// 列表接口输出数据结构
type GetListJobLevelRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      int32           `protobuf:"varint,1,opt,name=Page,proto3" json:"Page"`
	Size      int32           `protobuf:"varint,2,opt,name=Size,proto3" json:"Size"`
	TotalSize int32           `protobuf:"varint,3,opt,name=TotalSize,proto3" json:"TotalSize"`
	Data      []*JobLevelInfo `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data"`
}

func (x *GetListJobLevelRes) Reset() {
	*x = GetListJobLevelRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListJobLevelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListJobLevelRes) ProtoMessage() {}

func (x *GetListJobLevelRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListJobLevelRes.ProtoReflect.Descriptor instead.
func (*GetListJobLevelRes) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{6}
}

func (x *GetListJobLevelRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListJobLevelRes) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListJobLevelRes) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *GetListJobLevelRes) GetData() []*JobLevelInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 列表接口输入数据结构
type GetAllJobLevelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobLevel *JobLevelInfo `protobuf:"bytes,1,opt,name=JobLevel,proto3" json:"JobLevel"`
	Sort     OrderEnum     `protobuf:"varint,2,opt,name=Sort,proto3,enum=common.OrderEnum" json:"Sort"`
}

func (x *GetAllJobLevelReq) Reset() {
	*x = GetAllJobLevelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllJobLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllJobLevelReq) ProtoMessage() {}

func (x *GetAllJobLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllJobLevelReq.ProtoReflect.Descriptor instead.
func (*GetAllJobLevelReq) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllJobLevelReq) GetJobLevel() *JobLevelInfo {
	if x != nil {
		return x.JobLevel
	}
	return nil
}

func (x *GetAllJobLevelReq) GetSort() OrderEnum {
	if x != nil {
		return x.Sort
	}
	return OrderEnum_random
}

// 列表接口输出数据结构
type GetAllJobLevelRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*JobLevelInfo `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data"`
}

func (x *GetAllJobLevelRes) Reset() {
	*x = GetAllJobLevelRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllJobLevelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllJobLevelRes) ProtoMessage() {}

func (x *GetAllJobLevelRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllJobLevelRes.ProtoReflect.Descriptor instead.
func (*GetAllJobLevelRes) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllJobLevelRes) GetData() []*JobLevelInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 修改数据接口输入数据结构
type ModifyJobLevelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`        // v: required
	Name   string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`     // v: required
	Remark string `protobuf:"bytes,3,opt,name=Remark,proto3" json:"Remark"` // v: required
}

func (x *ModifyJobLevelReq) Reset() {
	*x = ModifyJobLevelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyJobLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyJobLevelReq) ProtoMessage() {}

func (x *ModifyJobLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyJobLevelReq.ProtoReflect.Descriptor instead.
func (*ModifyJobLevelReq) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyJobLevelReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModifyJobLevelReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModifyJobLevelReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 修改数据接口输出数据结构
type ModifyJobLevelRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobLevel *JobLevelInfo `protobuf:"bytes,1,opt,name=JobLevel,proto3" json:"JobLevel"`
}

func (x *ModifyJobLevelRes) Reset() {
	*x = ModifyJobLevelRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyJobLevelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyJobLevelRes) ProtoMessage() {}

func (x *ModifyJobLevelRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyJobLevelRes.ProtoReflect.Descriptor instead.
func (*ModifyJobLevelRes) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{10}
}

func (x *ModifyJobLevelRes) GetJobLevel() *JobLevelInfo {
	if x != nil {
		return x.JobLevel
	}
	return nil
}

// 删除数据接口输入数据结构
type DeleteJobLevelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"` // v: required
}

func (x *DeleteJobLevelReq) Reset() {
	*x = DeleteJobLevelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteJobLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobLevelReq) ProtoMessage() {}

func (x *DeleteJobLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobLevelReq.ProtoReflect.Descriptor instead.
func (*DeleteJobLevelReq) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteJobLevelReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除数据接口输出数据结构
type DeleteJobLevelRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess"` // v: required
	Msg       string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg"`              // v: required
}

func (x *DeleteJobLevelRes) Reset() {
	*x = DeleteJobLevelRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_v1_job_level_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteJobLevelRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobLevelRes) ProtoMessage() {}

func (x *DeleteJobLevelRes) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_job_level_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobLevelRes.ProtoReflect.Descriptor instead.
func (*DeleteJobLevelRes) Descriptor() ([]byte, []int) {
	return file_common_v1_job_level_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteJobLevelRes) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *DeleteJobLevelRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_common_v1_job_level_proto protoreflect.FileDescriptor

var file_common_v1_job_level_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x5f,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x22, 0x8a, 0x01, 0x0a, 0x0c, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x3f, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x22, 0x45, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x37, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f,
	0x6e, 0x65, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x45, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4a, 0x6f, 0x62, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x6e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x6c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x08, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x4a, 0x6f,
	0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x25, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x22, 0x3d, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4f, 0x0a, 0x11,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x45, 0x0a,
	0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4a, 0x6f,
	0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x4a, 0x6f, 0x62, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x6f,
	0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x2a, 0x2a,
	0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0a, 0x0a, 0x06, 0x72,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x10,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x61, 0x73, 0x63, 0x10, 0x02, 0x32, 0x99, 0x03, 0x0a, 0x08, 0x4a,
	0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x40, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x06, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x65, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x65, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x19,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x4a, 0x6f,
	0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x40, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x40, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12, 0x19, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4a, 0x6f, 0x62, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x19,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x6f,
	0x62, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6a, 0x31, 0x35, 0x37, 0x30, 0x36, 0x39, 0x33, 0x36, 0x35,
	0x39, 0x2f, 0x67, 0x66, 0x63, 0x71, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x5f, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_v1_job_level_proto_rawDescOnce sync.Once
	file_common_v1_job_level_proto_rawDescData = file_common_v1_job_level_proto_rawDesc
)

func file_common_v1_job_level_proto_rawDescGZIP() []byte {
	file_common_v1_job_level_proto_rawDescOnce.Do(func() {
		file_common_v1_job_level_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_v1_job_level_proto_rawDescData)
	})
	return file_common_v1_job_level_proto_rawDescData
}

var file_common_v1_job_level_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_job_level_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_common_v1_job_level_proto_goTypes = []interface{}{
	(OrderEnum)(0),             // 0: common.OrderEnum
	(*JobLevelInfo)(nil),       // 1: common.JobLevelInfo
	(*CreateJobLevelReq)(nil),  // 2: common.CreateJobLevelReq
	(*CreateJobLevelRes)(nil),  // 3: common.CreateJobLevelRes
	(*GetOneJobLevelReq)(nil),  // 4: common.GetOneJobLevelReq
	(*GetOneJobLevelRes)(nil),  // 5: common.GetOneJobLevelRes
	(*GetListJobLevelReq)(nil), // 6: common.GetListJobLevelReq
	(*GetListJobLevelRes)(nil), // 7: common.GetListJobLevelRes
	(*GetAllJobLevelReq)(nil),  // 8: common.GetAllJobLevelReq
	(*GetAllJobLevelRes)(nil),  // 9: common.GetAllJobLevelRes
	(*ModifyJobLevelReq)(nil),  // 10: common.ModifyJobLevelReq
	(*ModifyJobLevelRes)(nil),  // 11: common.ModifyJobLevelRes
	(*DeleteJobLevelReq)(nil),  // 12: common.DeleteJobLevelReq
	(*DeleteJobLevelRes)(nil),  // 13: common.DeleteJobLevelRes
}
var file_common_v1_job_level_proto_depIdxs = []int32{
	1,  // 0: common.CreateJobLevelRes.JobLevel:type_name -> common.JobLevelInfo
	1,  // 1: common.GetOneJobLevelRes.JobLevel:type_name -> common.JobLevelInfo
	1,  // 2: common.GetListJobLevelReq.JobLevel:type_name -> common.JobLevelInfo
	1,  // 3: common.GetListJobLevelRes.Data:type_name -> common.JobLevelInfo
	1,  // 4: common.GetAllJobLevelReq.JobLevel:type_name -> common.JobLevelInfo
	0,  // 5: common.GetAllJobLevelReq.Sort:type_name -> common.OrderEnum
	1,  // 6: common.GetAllJobLevelRes.Data:type_name -> common.JobLevelInfo
	1,  // 7: common.ModifyJobLevelRes.JobLevel:type_name -> common.JobLevelInfo
	2,  // 8: common.JobLevel.Create:input_type -> common.CreateJobLevelReq
	4,  // 9: common.JobLevel.GetOne:input_type -> common.GetOneJobLevelReq
	6,  // 10: common.JobLevel.GetList:input_type -> common.GetListJobLevelReq
	8,  // 11: common.JobLevel.GetAll:input_type -> common.GetAllJobLevelReq
	10, // 12: common.JobLevel.Modify:input_type -> common.ModifyJobLevelReq
	12, // 13: common.JobLevel.Delete:input_type -> common.DeleteJobLevelReq
	3,  // 14: common.JobLevel.Create:output_type -> common.CreateJobLevelRes
	5,  // 15: common.JobLevel.GetOne:output_type -> common.GetOneJobLevelRes
	7,  // 16: common.JobLevel.GetList:output_type -> common.GetListJobLevelRes
	9,  // 17: common.JobLevel.GetAll:output_type -> common.GetAllJobLevelRes
	11, // 18: common.JobLevel.Modify:output_type -> common.ModifyJobLevelRes
	13, // 19: common.JobLevel.Delete:output_type -> common.DeleteJobLevelRes
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_common_v1_job_level_proto_init() }
func file_common_v1_job_level_proto_init() {
	if File_common_v1_job_level_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_v1_job_level_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobLevelInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJobLevelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateJobLevelRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneJobLevelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneJobLevelRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListJobLevelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListJobLevelRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllJobLevelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllJobLevelRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyJobLevelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyJobLevelRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteJobLevelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_v1_job_level_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteJobLevelRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_v1_job_level_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_v1_job_level_proto_goTypes,
		DependencyIndexes: file_common_v1_job_level_proto_depIdxs,
		EnumInfos:         file_common_v1_job_level_proto_enumTypes,
		MessageInfos:      file_common_v1_job_level_proto_msgTypes,
	}.Build()
	File_common_v1_job_level_proto = out.File
	file_common_v1_job_level_proto_rawDesc = nil
	file_common_v1_job_level_proto_goTypes = nil
	file_common_v1_job_level_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JobLevelClient is the client API for JobLevel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobLevelClient interface {
	Create(ctx context.Context, in *CreateJobLevelReq, opts ...grpc.CallOption) (*CreateJobLevelRes, error)
	GetOne(ctx context.Context, in *GetOneJobLevelReq, opts ...grpc.CallOption) (*GetOneJobLevelRes, error)
	GetList(ctx context.Context, in *GetListJobLevelReq, opts ...grpc.CallOption) (*GetListJobLevelRes, error)
	GetAll(ctx context.Context, in *GetAllJobLevelReq, opts ...grpc.CallOption) (*GetAllJobLevelRes, error)
	Modify(ctx context.Context, in *ModifyJobLevelReq, opts ...grpc.CallOption) (*ModifyJobLevelRes, error)
	Delete(ctx context.Context, in *DeleteJobLevelReq, opts ...grpc.CallOption) (*DeleteJobLevelRes, error)
}

type jobLevelClient struct {
	cc grpc.ClientConnInterface
}

func NewJobLevelClient(cc grpc.ClientConnInterface) JobLevelClient {
	return &jobLevelClient{cc}
}

func (c *jobLevelClient) Create(ctx context.Context, in *CreateJobLevelReq, opts ...grpc.CallOption) (*CreateJobLevelRes, error) {
	out := new(CreateJobLevelRes)
	err := c.cc.Invoke(ctx, "/common.JobLevel/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobLevelClient) GetOne(ctx context.Context, in *GetOneJobLevelReq, opts ...grpc.CallOption) (*GetOneJobLevelRes, error) {
	out := new(GetOneJobLevelRes)
	err := c.cc.Invoke(ctx, "/common.JobLevel/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobLevelClient) GetList(ctx context.Context, in *GetListJobLevelReq, opts ...grpc.CallOption) (*GetListJobLevelRes, error) {
	out := new(GetListJobLevelRes)
	err := c.cc.Invoke(ctx, "/common.JobLevel/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobLevelClient) GetAll(ctx context.Context, in *GetAllJobLevelReq, opts ...grpc.CallOption) (*GetAllJobLevelRes, error) {
	out := new(GetAllJobLevelRes)
	err := c.cc.Invoke(ctx, "/common.JobLevel/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobLevelClient) Modify(ctx context.Context, in *ModifyJobLevelReq, opts ...grpc.CallOption) (*ModifyJobLevelRes, error) {
	out := new(ModifyJobLevelRes)
	err := c.cc.Invoke(ctx, "/common.JobLevel/Modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobLevelClient) Delete(ctx context.Context, in *DeleteJobLevelReq, opts ...grpc.CallOption) (*DeleteJobLevelRes, error) {
	out := new(DeleteJobLevelRes)
	err := c.cc.Invoke(ctx, "/common.JobLevel/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobLevelServer is the server API for JobLevel service.
type JobLevelServer interface {
	Create(context.Context, *CreateJobLevelReq) (*CreateJobLevelRes, error)
	GetOne(context.Context, *GetOneJobLevelReq) (*GetOneJobLevelRes, error)
	GetList(context.Context, *GetListJobLevelReq) (*GetListJobLevelRes, error)
	GetAll(context.Context, *GetAllJobLevelReq) (*GetAllJobLevelRes, error)
	Modify(context.Context, *ModifyJobLevelReq) (*ModifyJobLevelRes, error)
	Delete(context.Context, *DeleteJobLevelReq) (*DeleteJobLevelRes, error)
}

// UnimplementedJobLevelServer can be embedded to have forward compatible implementations.
type UnimplementedJobLevelServer struct {
}

func (*UnimplementedJobLevelServer) Create(context.Context, *CreateJobLevelReq) (*CreateJobLevelRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedJobLevelServer) GetOne(context.Context, *GetOneJobLevelReq) (*GetOneJobLevelRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (*UnimplementedJobLevelServer) GetList(context.Context, *GetListJobLevelReq) (*GetListJobLevelRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedJobLevelServer) GetAll(context.Context, *GetAllJobLevelReq) (*GetAllJobLevelRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedJobLevelServer) Modify(context.Context, *ModifyJobLevelReq) (*ModifyJobLevelRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (*UnimplementedJobLevelServer) Delete(context.Context, *DeleteJobLevelReq) (*DeleteJobLevelRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterJobLevelServer(s *grpc.Server, srv JobLevelServer) {
	s.RegisterService(&_JobLevel_serviceDesc, srv)
}

func _JobLevel_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateJobLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobLevelServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.JobLevel/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobLevelServer).Create(ctx, req.(*CreateJobLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobLevel_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneJobLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobLevelServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.JobLevel/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobLevelServer).GetOne(ctx, req.(*GetOneJobLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobLevel_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListJobLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobLevelServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.JobLevel/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobLevelServer).GetList(ctx, req.(*GetListJobLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobLevel_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllJobLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobLevelServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.JobLevel/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobLevelServer).GetAll(ctx, req.(*GetAllJobLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobLevel_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyJobLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobLevelServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.JobLevel/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobLevelServer).Modify(ctx, req.(*ModifyJobLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobLevel_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobLevelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobLevelServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/common.JobLevel/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobLevelServer).Delete(ctx, req.(*DeleteJobLevelReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobLevel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "common.JobLevel",
	HandlerType: (*JobLevelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _JobLevel_Create_Handler,
		},
		{
			MethodName: "GetOne",
			Handler:    _JobLevel_GetOne_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _JobLevel_GetList_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _JobLevel_GetAll_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _JobLevel_Modify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _JobLevel_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/v1/job_level.proto",
}
