// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: config/product/v1/roles.proto

package v1

import (
	context "context"
	reflect "reflect"
	sync "sync"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 项目角色配置信息
type RolesInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`                // ""
	Name       string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`             // 角色名
	Pid        int32  `protobuf:"varint,3,opt,name=Pid,proto3" json:"Pid"`              // 上级角色
	Explain    string `protobuf:"bytes,4,opt,name=Explain,proto3" json:"Explain"`       // 角色与职责说明
	Remark     string `protobuf:"bytes,5,opt,name=Remark,proto3" json:"Remark"`         // 预留备注说明信息
	CreateTime string `protobuf:"bytes,6,opt,name=CreateTime,proto3" json:"CreateTime"` // "新增数据时间"
	UpdateTime string `protobuf:"bytes,7,opt,name=UpdateTime,proto3" json:"UpdateTime"` // "最新更新数据"
}

func (x *RolesInfo) Reset() {
	*x = RolesInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_product_v1_roles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RolesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolesInfo) ProtoMessage() {}

func (x *RolesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_config_product_v1_roles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolesInfo.ProtoReflect.Descriptor instead.
func (*RolesInfo) Descriptor() ([]byte, []int) {
	return file_config_product_v1_roles_proto_rawDescGZIP(), []int{0}
}

func (x *RolesInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RolesInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RolesInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RolesInfo) GetExplain() string {
	if x != nil {
		return x.Explain
	}
	return ""
}

func (x *RolesInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *RolesInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *RolesInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

// 创建数据接口输入数据结构
type CreateRolesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name"`       // 角色名
	Pid     int32  `protobuf:"varint,2,opt,name=Pid,proto3" json:"Pid"`        // 上级角色
	Explain string `protobuf:"bytes,3,opt,name=Explain,proto3" json:"Explain"` // 角色与职责说明
	Remark  string `protobuf:"bytes,4,opt,name=Remark,proto3" json:"Remark"`   // 预留备注说明信息
}

func (x *CreateRolesReq) Reset() {
	*x = CreateRolesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_product_v1_roles_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRolesReq) ProtoMessage() {}

func (x *CreateRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_product_v1_roles_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRolesReq.ProtoReflect.Descriptor instead.
func (*CreateRolesReq) Descriptor() ([]byte, []int) {
	return file_config_product_v1_roles_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRolesReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRolesReq) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CreateRolesReq) GetExplain() string {
	if x != nil {
		return x.Explain
	}
	return ""
}

func (x *CreateRolesReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 创建数据接口输出数据结构
type CreateRolesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles *RolesInfo `protobuf:"bytes,1,opt,name=Roles,proto3" json:"Roles"`
}

func (x *CreateRolesRes) Reset() {
	*x = CreateRolesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_product_v1_roles_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRolesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRolesRes) ProtoMessage() {}

func (x *CreateRolesRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_product_v1_roles_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRolesRes.ProtoReflect.Descriptor instead.
func (*CreateRolesRes) Descriptor() ([]byte, []int) {
	return file_config_product_v1_roles_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRolesRes) GetRoles() *RolesInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 获取详情接口输入数据结构
type GetOneRolesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles *RolesInfo `protobuf:"bytes,1,opt,name=Roles,proto3" json:"Roles"`
}

func (x *GetOneRolesReq) Reset() {
	*x = GetOneRolesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_product_v1_roles_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRolesReq) ProtoMessage() {}

func (x *GetOneRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_product_v1_roles_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRolesReq.ProtoReflect.Descriptor instead.
func (*GetOneRolesReq) Descriptor() ([]byte, []int) {
	return file_config_product_v1_roles_proto_rawDescGZIP(), []int{3}
}

func (x *GetOneRolesReq) GetRoles() *RolesInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 获取详情接口输出数据结构
type GetOneRolesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles *RolesInfo `protobuf:"bytes,1,opt,name=Roles,proto3" json:"Roles"`
}

func (x *GetOneRolesRes) Reset() {
	*x = GetOneRolesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_product_v1_roles_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneRolesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRolesRes) ProtoMessage() {}

func (x *GetOneRolesRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_product_v1_roles_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRolesRes.ProtoReflect.Descriptor instead.
func (*GetOneRolesRes) Descriptor() ([]byte, []int) {
	return file_config_product_v1_roles_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneRolesRes) GetRoles() *RolesInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 列表接口输入数据结构
type GetListRolesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32      `protobuf:"varint,1,opt,name=Page,proto3" json:"Page"`
	Size  int32      `protobuf:"varint,2,opt,name=Size,proto3" json:"Size"`
	Roles *RolesInfo `protobuf:"bytes,3,opt,name=Roles,proto3" json:"Roles"`
}

func (x *GetListRolesReq) Reset() {
	*x = GetListRolesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_product_v1_roles_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRolesReq) ProtoMessage() {}

func (x *GetListRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_product_v1_roles_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRolesReq.ProtoReflect.Descriptor instead.
func (*GetListRolesReq) Descriptor() ([]byte, []int) {
	return file_config_product_v1_roles_proto_rawDescGZIP(), []int{5}
}

func (x *GetListRolesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListRolesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListRolesReq) GetRoles() *RolesInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 列表接口输出数据结构
type GetListRolesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      int32        `protobuf:"varint,1,opt,name=Page,proto3" json:"Page"`
	Size      int32        `protobuf:"varint,2,opt,name=Size,proto3" json:"Size"`
	TotalSize int32        `protobuf:"varint,3,opt,name=TotalSize,proto3" json:"TotalSize"`
	Data      []*RolesInfo `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data"`
}

func (x *GetListRolesRes) Reset() {
	*x = GetListRolesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_product_v1_roles_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListRolesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListRolesRes) ProtoMessage() {}

func (x *GetListRolesRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_product_v1_roles_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListRolesRes.ProtoReflect.Descriptor instead.
func (*GetListRolesRes) Descriptor() ([]byte, []int) {
	return file_config_product_v1_roles_proto_rawDescGZIP(), []int{6}
}

func (x *GetListRolesRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListRolesRes) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListRolesRes) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *GetListRolesRes) GetData() []*RolesInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 修改数据接口输入数据结构
type ModifyRolesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name"`       // 角色名
	Pid     int32  `protobuf:"varint,2,opt,name=Pid,proto3" json:"Pid"`        // 上级角色
	Explain string `protobuf:"bytes,3,opt,name=Explain,proto3" json:"Explain"` // 角色与职责说明
	Remark  string `protobuf:"bytes,4,opt,name=Remark,proto3" json:"Remark"`   // 预留备注说明信息
	Id      int32  `protobuf:"varint,5,opt,name=Id,proto3" json:"Id"`          // v: required
}

func (x *ModifyRolesReq) Reset() {
	*x = ModifyRolesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_product_v1_roles_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyRolesReq) ProtoMessage() {}

func (x *ModifyRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_product_v1_roles_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyRolesReq.ProtoReflect.Descriptor instead.
func (*ModifyRolesReq) Descriptor() ([]byte, []int) {
	return file_config_product_v1_roles_proto_rawDescGZIP(), []int{7}
}

func (x *ModifyRolesReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModifyRolesReq) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ModifyRolesReq) GetExplain() string {
	if x != nil {
		return x.Explain
	}
	return ""
}

func (x *ModifyRolesReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ModifyRolesReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 修改数据接口输出数据结构
type ModifyRolesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles *RolesInfo `protobuf:"bytes,3,opt,name=Roles,proto3" json:"Roles"`
}

func (x *ModifyRolesRes) Reset() {
	*x = ModifyRolesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_product_v1_roles_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyRolesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyRolesRes) ProtoMessage() {}

func (x *ModifyRolesRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_product_v1_roles_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyRolesRes.ProtoReflect.Descriptor instead.
func (*ModifyRolesRes) Descriptor() ([]byte, []int) {
	return file_config_product_v1_roles_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyRolesRes) GetRoles() *RolesInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

// 删除数据接口输入数据结构
type DeleteRolesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"` // v: required
}

func (x *DeleteRolesReq) Reset() {
	*x = DeleteRolesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_product_v1_roles_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRolesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRolesReq) ProtoMessage() {}

func (x *DeleteRolesReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_product_v1_roles_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRolesReq.ProtoReflect.Descriptor instead.
func (*DeleteRolesReq) Descriptor() ([]byte, []int) {
	return file_config_product_v1_roles_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRolesReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除数据接口输出数据结构
type DeleteRolesRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess"` // v: required
	Msg       string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg"`              // v: required
}

func (x *DeleteRolesRes) Reset() {
	*x = DeleteRolesRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_product_v1_roles_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRolesRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRolesRes) ProtoMessage() {}

func (x *DeleteRolesRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_product_v1_roles_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRolesRes.ProtoReflect.Descriptor instead.
func (*DeleteRolesRes) Descriptor() ([]byte, []int) {
	return file_config_product_v1_roles_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRolesRes) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *DeleteRolesRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_config_product_v1_roles_proto protoreflect.FileDescriptor

var file_config_product_v1_roles_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x2f, 0x76, 0x31, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xb3, 0x01, 0x0a, 0x09, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x45,
	0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x78,
	0x70, 0x6c, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1e, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x68, 0x0a,
	0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x50, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x39, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x52, 0x6f, 0x6c,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x52, 0x6f, 0x6c,
	0x65, 0x73, 0x22, 0x39, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x27, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x39, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12,
	0x27, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x62, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x50,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x7e, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x78, 0x0a, 0x0e,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x50, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x0e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x22, 0x20, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x73, 0x67, 0x32, 0xb6, 0x02, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12,
	0x3a, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x06, 0x47,
	0x65, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x52, 0x6f, 0x6c,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x17, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x12, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x37,
	0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6a, 0x31,
	0x35, 0x37, 0x30, 0x36, 0x39, 0x33, 0x36, 0x35, 0x39, 0x2f, 0x67, 0x66, 0x63, 0x71, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_product_v1_roles_proto_rawDescOnce sync.Once
	file_config_product_v1_roles_proto_rawDescData = file_config_product_v1_roles_proto_rawDesc
)

func file_config_product_v1_roles_proto_rawDescGZIP() []byte {
	file_config_product_v1_roles_proto_rawDescOnce.Do(func() {
		file_config_product_v1_roles_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_product_v1_roles_proto_rawDescData)
	})
	return file_config_product_v1_roles_proto_rawDescData
}

var file_config_product_v1_roles_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_config_product_v1_roles_proto_goTypes = []interface{}{
	(*RolesInfo)(nil),       // 0: config.RolesInfo
	(*CreateRolesReq)(nil),  // 1: config.CreateRolesReq
	(*CreateRolesRes)(nil),  // 2: config.CreateRolesRes
	(*GetOneRolesReq)(nil),  // 3: config.GetOneRolesReq
	(*GetOneRolesRes)(nil),  // 4: config.GetOneRolesRes
	(*GetListRolesReq)(nil), // 5: config.GetListRolesReq
	(*GetListRolesRes)(nil), // 6: config.GetListRolesRes
	(*ModifyRolesReq)(nil),  // 7: config.ModifyRolesReq
	(*ModifyRolesRes)(nil),  // 8: config.ModifyRolesRes
	(*DeleteRolesReq)(nil),  // 9: config.DeleteRolesReq
	(*DeleteRolesRes)(nil),  // 10: config.DeleteRolesRes
}
var file_config_product_v1_roles_proto_depIdxs = []int32{
	0,  // 0: config.CreateRolesRes.Roles:type_name -> config.RolesInfo
	0,  // 1: config.GetOneRolesReq.Roles:type_name -> config.RolesInfo
	0,  // 2: config.GetOneRolesRes.Roles:type_name -> config.RolesInfo
	0,  // 3: config.GetListRolesReq.Roles:type_name -> config.RolesInfo
	0,  // 4: config.GetListRolesRes.Data:type_name -> config.RolesInfo
	0,  // 5: config.ModifyRolesRes.Roles:type_name -> config.RolesInfo
	1,  // 6: config.Roles.Create:input_type -> config.CreateRolesReq
	3,  // 7: config.Roles.GetOne:input_type -> config.GetOneRolesReq
	5,  // 8: config.Roles.GetList:input_type -> config.GetListRolesReq
	7,  // 9: config.Roles.Modify:input_type -> config.ModifyRolesReq
	9,  // 10: config.Roles.Delete:input_type -> config.DeleteRolesReq
	2,  // 11: config.Roles.Create:output_type -> config.CreateRolesRes
	4,  // 12: config.Roles.GetOne:output_type -> config.GetOneRolesRes
	6,  // 13: config.Roles.GetList:output_type -> config.GetListRolesRes
	8,  // 14: config.Roles.Modify:output_type -> config.ModifyRolesRes
	10, // 15: config.Roles.Delete:output_type -> config.DeleteRolesRes
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_config_product_v1_roles_proto_init() }
func file_config_product_v1_roles_proto_init() {
	if File_config_product_v1_roles_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_product_v1_roles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RolesInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_product_v1_roles_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRolesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_product_v1_roles_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRolesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_product_v1_roles_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneRolesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_product_v1_roles_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneRolesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_product_v1_roles_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListRolesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_product_v1_roles_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListRolesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_product_v1_roles_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyRolesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_product_v1_roles_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyRolesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_product_v1_roles_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRolesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_product_v1_roles_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRolesRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_product_v1_roles_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_product_v1_roles_proto_goTypes,
		DependencyIndexes: file_config_product_v1_roles_proto_depIdxs,
		MessageInfos:      file_config_product_v1_roles_proto_msgTypes,
	}.Build()
	File_config_product_v1_roles_proto = out.File
	file_config_product_v1_roles_proto_rawDesc = nil
	file_config_product_v1_roles_proto_goTypes = nil
	file_config_product_v1_roles_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RolesClient is the client API for Roles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RolesClient interface {
	Create(ctx context.Context, in *CreateRolesReq, opts ...grpc.CallOption) (*CreateRolesRes, error)
	GetOne(ctx context.Context, in *GetOneRolesReq, opts ...grpc.CallOption) (*GetOneRolesRes, error)
	GetList(ctx context.Context, in *GetListRolesReq, opts ...grpc.CallOption) (*GetListRolesRes, error)
	Modify(ctx context.Context, in *ModifyRolesReq, opts ...grpc.CallOption) (*ModifyRolesRes, error)
	Delete(ctx context.Context, in *DeleteRolesReq, opts ...grpc.CallOption) (*DeleteRolesRes, error)
}

type rolesClient struct {
	cc grpc.ClientConnInterface
}

func NewRolesClient(cc grpc.ClientConnInterface) RolesClient {
	return &rolesClient{cc}
}

func (c *rolesClient) Create(ctx context.Context, in *CreateRolesReq, opts ...grpc.CallOption) (*CreateRolesRes, error) {
	out := new(CreateRolesRes)
	err := c.cc.Invoke(ctx, "/config.Roles/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) GetOne(ctx context.Context, in *GetOneRolesReq, opts ...grpc.CallOption) (*GetOneRolesRes, error) {
	out := new(GetOneRolesRes)
	err := c.cc.Invoke(ctx, "/config.Roles/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) GetList(ctx context.Context, in *GetListRolesReq, opts ...grpc.CallOption) (*GetListRolesRes, error) {
	out := new(GetListRolesRes)
	err := c.cc.Invoke(ctx, "/config.Roles/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) Modify(ctx context.Context, in *ModifyRolesReq, opts ...grpc.CallOption) (*ModifyRolesRes, error) {
	out := new(ModifyRolesRes)
	err := c.cc.Invoke(ctx, "/config.Roles/Modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rolesClient) Delete(ctx context.Context, in *DeleteRolesReq, opts ...grpc.CallOption) (*DeleteRolesRes, error) {
	out := new(DeleteRolesRes)
	err := c.cc.Invoke(ctx, "/config.Roles/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RolesServer is the server API for Roles service.
type RolesServer interface {
	Create(context.Context, *CreateRolesReq) (*CreateRolesRes, error)
	GetOne(context.Context, *GetOneRolesReq) (*GetOneRolesRes, error)
	GetList(context.Context, *GetListRolesReq) (*GetListRolesRes, error)
	Modify(context.Context, *ModifyRolesReq) (*ModifyRolesRes, error)
	Delete(context.Context, *DeleteRolesReq) (*DeleteRolesRes, error)
}

// UnimplementedRolesServer can be embedded to have forward compatible implementations.
type UnimplementedRolesServer struct {
}

func (*UnimplementedRolesServer) Create(context.Context, *CreateRolesReq) (*CreateRolesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedRolesServer) GetOne(context.Context, *GetOneRolesReq) (*GetOneRolesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (*UnimplementedRolesServer) GetList(context.Context, *GetListRolesReq) (*GetListRolesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedRolesServer) Modify(context.Context, *ModifyRolesReq) (*ModifyRolesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (*UnimplementedRolesServer) Delete(context.Context, *DeleteRolesReq) (*DeleteRolesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterRolesServer(s *grpc.Server, srv RolesServer) {
	s.RegisterService(&_Roles_serviceDesc, srv)
}

func _Roles_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.Roles/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).Create(ctx, req.(*CreateRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roles_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.Roles/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).GetOne(ctx, req.(*GetOneRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roles_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.Roles/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).GetList(ctx, req.(*GetListRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roles_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.Roles/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).Modify(ctx, req.(*ModifyRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Roles_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RolesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.Roles/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RolesServer).Delete(ctx, req.(*DeleteRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Roles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "config.Roles",
	HandlerType: (*RolesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Roles_Create_Handler,
		},
		{
			MethodName: "GetOne",
			Handler:    _Roles_GetOne_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _Roles_GetList_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _Roles_Modify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Roles_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config/product/v1/roles.proto",
}
