// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: config/inspirit/v1/budget_access.proto

package v1

import (
	context "context"
	reflect "reflect"
	sync "sync"

	v1 "github.com/lj1570693659/gfcq_protoc/config/product/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 项目得分-预算额度配置信息
type BudgetAssessInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32             `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	ScoreMin    uint32            `protobuf:"varint,2,opt,name=ScoreMin,proto3" json:"ScoreMin"`                                  // 分值下限
	ScoreMax    uint32            `protobuf:"varint,3,opt,name=ScoreMax,proto3" json:"ScoreMax"`                                  // 分值上限
	ScoreRange  v1.ScoreRangeEnum `protobuf:"varint,4,opt,name=ScoreRange,proto3,enum=config.ScoreRangeEnum" json:"ScoreRange"`   // 分数区间包含关系（1：左闭右开，2：左开右闭）
	BudgetMin   float32           `protobuf:"fixed32,5,opt,name=BudgetMin,proto3" json:"BudgetMin"`                               // 预算额度下限
	BudgetMax   float32           `protobuf:"fixed32,6,opt,name=BudgetMax,proto3" json:"BudgetMax"`                               // 预算额度上线
	BudgetRange v1.ScoreRangeEnum `protobuf:"varint,7,opt,name=BudgetRange,proto3,enum=config.ScoreRangeEnum" json:"BudgetRange"` // 额度区间包含关系（1：左闭右开，2：左开右闭）
	Remark      string            `protobuf:"bytes,8,opt,name=Remark,proto3" json:"Remark"`                                       // 预留备注说明信息
	CreateTime  string            `protobuf:"bytes,9,opt,name=CreateTime,proto3" json:"CreateTime"`                               // 数据新增时间
	UpdateTime  string            `protobuf:"bytes,10,opt,name=UpdateTime,proto3" json:"UpdateTime"`                              // 最后一次更新数据时间
}

func (x *BudgetAssessInfo) Reset() {
	*x = BudgetAssessInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BudgetAssessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetAssessInfo) ProtoMessage() {}

func (x *BudgetAssessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetAssessInfo.ProtoReflect.Descriptor instead.
func (*BudgetAssessInfo) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{0}
}

func (x *BudgetAssessInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BudgetAssessInfo) GetScoreMin() uint32 {
	if x != nil {
		return x.ScoreMin
	}
	return 0
}

func (x *BudgetAssessInfo) GetScoreMax() uint32 {
	if x != nil {
		return x.ScoreMax
	}
	return 0
}

func (x *BudgetAssessInfo) GetScoreRange() v1.ScoreRangeEnum {
	if x != nil {
		return x.ScoreRange
	}
	return v1.ScoreRangeEnum(0)
}

func (x *BudgetAssessInfo) GetBudgetMin() float32 {
	if x != nil {
		return x.BudgetMin
	}
	return 0
}

func (x *BudgetAssessInfo) GetBudgetMax() float32 {
	if x != nil {
		return x.BudgetMax
	}
	return 0
}

func (x *BudgetAssessInfo) GetBudgetRange() v1.ScoreRangeEnum {
	if x != nil {
		return x.BudgetRange
	}
	return v1.ScoreRangeEnum(0)
}

func (x *BudgetAssessInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BudgetAssessInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *BudgetAssessInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

// 创建数据接口输入数据结构
type CreateBudgetAssessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScoreMin    uint32            `protobuf:"varint,1,opt,name=ScoreMin,proto3" json:"ScoreMin"`                                  // 分值下限
	ScoreMax    uint32            `protobuf:"varint,2,opt,name=ScoreMax,proto3" json:"ScoreMax"`                                  // 分值上限
	ScoreRange  v1.ScoreRangeEnum `protobuf:"varint,3,opt,name=ScoreRange,proto3,enum=config.ScoreRangeEnum" json:"ScoreRange"`   // 分数区间包含关系（1：左闭右开，2：左开右闭）
	BudgetMin   float32           `protobuf:"fixed32,4,opt,name=BudgetMin,proto3" json:"BudgetMin"`                               // 预算额度下限
	BudgetMax   float32           `protobuf:"fixed32,5,opt,name=BudgetMax,proto3" json:"BudgetMax"`                               // 预算额度上线
	BudgetRange v1.ScoreRangeEnum `protobuf:"varint,6,opt,name=BudgetRange,proto3,enum=config.ScoreRangeEnum" json:"BudgetRange"` // 额度区间包含关系（1：左闭右开，2：左开右闭）
	Remark      string            `protobuf:"bytes,7,opt,name=Remark,proto3" json:"Remark"`                                       // 预留备注说明信息
}

func (x *CreateBudgetAssessReq) Reset() {
	*x = CreateBudgetAssessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBudgetAssessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetAssessReq) ProtoMessage() {}

func (x *CreateBudgetAssessReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetAssessReq.ProtoReflect.Descriptor instead.
func (*CreateBudgetAssessReq) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBudgetAssessReq) GetScoreMin() uint32 {
	if x != nil {
		return x.ScoreMin
	}
	return 0
}

func (x *CreateBudgetAssessReq) GetScoreMax() uint32 {
	if x != nil {
		return x.ScoreMax
	}
	return 0
}

func (x *CreateBudgetAssessReq) GetScoreRange() v1.ScoreRangeEnum {
	if x != nil {
		return x.ScoreRange
	}
	return v1.ScoreRangeEnum(0)
}

func (x *CreateBudgetAssessReq) GetBudgetMin() float32 {
	if x != nil {
		return x.BudgetMin
	}
	return 0
}

func (x *CreateBudgetAssessReq) GetBudgetMax() float32 {
	if x != nil {
		return x.BudgetMax
	}
	return 0
}

func (x *CreateBudgetAssessReq) GetBudgetRange() v1.ScoreRangeEnum {
	if x != nil {
		return x.BudgetRange
	}
	return v1.ScoreRangeEnum(0)
}

func (x *CreateBudgetAssessReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 创建数据接口输出数据结构
type CreateBudgetAssessRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BudgetAssess *BudgetAssessInfo `protobuf:"bytes,1,opt,name=BudgetAssess,proto3" json:"BudgetAssess"`
}

func (x *CreateBudgetAssessRes) Reset() {
	*x = CreateBudgetAssessRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBudgetAssessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBudgetAssessRes) ProtoMessage() {}

func (x *CreateBudgetAssessRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBudgetAssessRes.ProtoReflect.Descriptor instead.
func (*CreateBudgetAssessRes) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBudgetAssessRes) GetBudgetAssess() *BudgetAssessInfo {
	if x != nil {
		return x.BudgetAssess
	}
	return nil
}

// 获取详情接口输入数据结构
type GetOneBudgetAssessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BudgetAssess *BudgetAssessInfo `protobuf:"bytes,1,opt,name=BudgetAssess,proto3" json:"BudgetAssess"`
}

func (x *GetOneBudgetAssessReq) Reset() {
	*x = GetOneBudgetAssessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneBudgetAssessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneBudgetAssessReq) ProtoMessage() {}

func (x *GetOneBudgetAssessReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneBudgetAssessReq.ProtoReflect.Descriptor instead.
func (*GetOneBudgetAssessReq) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{3}
}

func (x *GetOneBudgetAssessReq) GetBudgetAssess() *BudgetAssessInfo {
	if x != nil {
		return x.BudgetAssess
	}
	return nil
}

// 获取详情接口输出数据结构
type GetOneBudgetAssessRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BudgetAssess *BudgetAssessInfo `protobuf:"bytes,1,opt,name=BudgetAssess,proto3" json:"BudgetAssess"`
}

func (x *GetOneBudgetAssessRes) Reset() {
	*x = GetOneBudgetAssessRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOneBudgetAssessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneBudgetAssessRes) ProtoMessage() {}

func (x *GetOneBudgetAssessRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneBudgetAssessRes.ProtoReflect.Descriptor instead.
func (*GetOneBudgetAssessRes) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneBudgetAssessRes) GetBudgetAssess() *BudgetAssessInfo {
	if x != nil {
		return x.BudgetAssess
	}
	return nil
}

// 列表接口输入数据结构
type GetListBudgetAssessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page         int32             `protobuf:"varint,1,opt,name=Page,proto3" json:"Page"`
	Size         int32             `protobuf:"varint,2,opt,name=Size,proto3" json:"Size"`
	BudgetAssess *BudgetAssessInfo `protobuf:"bytes,3,opt,name=BudgetAssess,proto3" json:"BudgetAssess"`
}

func (x *GetListBudgetAssessReq) Reset() {
	*x = GetListBudgetAssessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListBudgetAssessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBudgetAssessReq) ProtoMessage() {}

func (x *GetListBudgetAssessReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListBudgetAssessReq.ProtoReflect.Descriptor instead.
func (*GetListBudgetAssessReq) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{5}
}

func (x *GetListBudgetAssessReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListBudgetAssessReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListBudgetAssessReq) GetBudgetAssess() *BudgetAssessInfo {
	if x != nil {
		return x.BudgetAssess
	}
	return nil
}

// 列表接口输出数据结构
type GetListBudgetAssessRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      int32               `protobuf:"varint,1,opt,name=Page,proto3" json:"Page"`
	Size      int32               `protobuf:"varint,2,opt,name=Size,proto3" json:"Size"`
	TotalSize int32               `protobuf:"varint,3,opt,name=TotalSize,proto3" json:"TotalSize"`
	Data      []*BudgetAssessInfo `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data"`
}

func (x *GetListBudgetAssessRes) Reset() {
	*x = GetListBudgetAssessRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListBudgetAssessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListBudgetAssessRes) ProtoMessage() {}

func (x *GetListBudgetAssessRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListBudgetAssessRes.ProtoReflect.Descriptor instead.
func (*GetListBudgetAssessRes) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{6}
}

func (x *GetListBudgetAssessRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListBudgetAssessRes) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListBudgetAssessRes) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *GetListBudgetAssessRes) GetData() []*BudgetAssessInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 列表接口输入数据结构
type GetAllBudgetAssessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BudgetAssess *BudgetAssessInfo `protobuf:"bytes,1,opt,name=BudgetAssess,proto3" json:"BudgetAssess"`
}

func (x *GetAllBudgetAssessReq) Reset() {
	*x = GetAllBudgetAssessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBudgetAssessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBudgetAssessReq) ProtoMessage() {}

func (x *GetAllBudgetAssessReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBudgetAssessReq.ProtoReflect.Descriptor instead.
func (*GetAllBudgetAssessReq) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllBudgetAssessReq) GetBudgetAssess() *BudgetAssessInfo {
	if x != nil {
		return x.BudgetAssess
	}
	return nil
}

// 列表接口输出数据结构
type GetAllBudgetAssessRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*BudgetAssessInfo `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data"`
}

func (x *GetAllBudgetAssessRes) Reset() {
	*x = GetAllBudgetAssessRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBudgetAssessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBudgetAssessRes) ProtoMessage() {}

func (x *GetAllBudgetAssessRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBudgetAssessRes.ProtoReflect.Descriptor instead.
func (*GetAllBudgetAssessRes) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllBudgetAssessRes) GetData() []*BudgetAssessInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 修改数据接口输入数据结构
type ModifyBudgetAssessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScoreMin    uint32            `protobuf:"varint,1,opt,name=ScoreMin,proto3" json:"ScoreMin"`                                  // 分值下限
	ScoreMax    uint32            `protobuf:"varint,2,opt,name=ScoreMax,proto3" json:"ScoreMax"`                                  // 分值上限
	ScoreRange  v1.ScoreRangeEnum `protobuf:"varint,3,opt,name=ScoreRange,proto3,enum=config.ScoreRangeEnum" json:"ScoreRange"`   // 分数区间包含关系（1：左闭右开，2：左开右闭）
	BudgetMin   float32           `protobuf:"fixed32,4,opt,name=BudgetMin,proto3" json:"BudgetMin"`                               // 预算额度下限
	BudgetMax   float32           `protobuf:"fixed32,5,opt,name=BudgetMax,proto3" json:"BudgetMax"`                               // 预算额度上线
	BudgetRange v1.ScoreRangeEnum `protobuf:"varint,6,opt,name=BudgetRange,proto3,enum=config.ScoreRangeEnum" json:"BudgetRange"` // 额度区间包含关系（1：左闭右开，2：左开右闭）
	Remark      string            `protobuf:"bytes,7,opt,name=Remark,proto3" json:"Remark"`                                       // 预留备注说明信息
	Id          int32             `protobuf:"varint,8,opt,name=Id,proto3" json:"Id"`                                              // v: required
}

func (x *ModifyBudgetAssessReq) Reset() {
	*x = ModifyBudgetAssessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyBudgetAssessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyBudgetAssessReq) ProtoMessage() {}

func (x *ModifyBudgetAssessReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyBudgetAssessReq.ProtoReflect.Descriptor instead.
func (*ModifyBudgetAssessReq) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyBudgetAssessReq) GetScoreMin() uint32 {
	if x != nil {
		return x.ScoreMin
	}
	return 0
}

func (x *ModifyBudgetAssessReq) GetScoreMax() uint32 {
	if x != nil {
		return x.ScoreMax
	}
	return 0
}

func (x *ModifyBudgetAssessReq) GetScoreRange() v1.ScoreRangeEnum {
	if x != nil {
		return x.ScoreRange
	}
	return v1.ScoreRangeEnum(0)
}

func (x *ModifyBudgetAssessReq) GetBudgetMin() float32 {
	if x != nil {
		return x.BudgetMin
	}
	return 0
}

func (x *ModifyBudgetAssessReq) GetBudgetMax() float32 {
	if x != nil {
		return x.BudgetMax
	}
	return 0
}

func (x *ModifyBudgetAssessReq) GetBudgetRange() v1.ScoreRangeEnum {
	if x != nil {
		return x.BudgetRange
	}
	return v1.ScoreRangeEnum(0)
}

func (x *ModifyBudgetAssessReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ModifyBudgetAssessReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 修改数据接口输出数据结构
type ModifyBudgetAssessRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BudgetAssess *BudgetAssessInfo `protobuf:"bytes,1,opt,name=BudgetAssess,proto3" json:"BudgetAssess"`
}

func (x *ModifyBudgetAssessRes) Reset() {
	*x = ModifyBudgetAssessRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyBudgetAssessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyBudgetAssessRes) ProtoMessage() {}

func (x *ModifyBudgetAssessRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyBudgetAssessRes.ProtoReflect.Descriptor instead.
func (*ModifyBudgetAssessRes) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{10}
}

func (x *ModifyBudgetAssessRes) GetBudgetAssess() *BudgetAssessInfo {
	if x != nil {
		return x.BudgetAssess
	}
	return nil
}

// 删除数据接口输入数据结构
type DeleteBudgetAssessReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"` // v: required
}

func (x *DeleteBudgetAssessReq) Reset() {
	*x = DeleteBudgetAssessReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBudgetAssessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBudgetAssessReq) ProtoMessage() {}

func (x *DeleteBudgetAssessReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBudgetAssessReq.ProtoReflect.Descriptor instead.
func (*DeleteBudgetAssessReq) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteBudgetAssessReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除数据接口输出数据结构
type DeleteBudgetAssessRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess"` // v: required
	Msg       string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg"`              // v: required
}

func (x *DeleteBudgetAssessRes) Reset() {
	*x = DeleteBudgetAssessRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBudgetAssessRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBudgetAssessRes) ProtoMessage() {}

func (x *DeleteBudgetAssessRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_budget_access_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBudgetAssessRes.ProtoReflect.Descriptor instead.
func (*DeleteBudgetAssessRes) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_budget_access_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBudgetAssessRes) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *DeleteBudgetAssessRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_config_inspirit_v1_budget_access_proto protoreflect.FileDescriptor

var file_config_inspirit_v1_budget_access_proto_rawDesc = []byte{
	0x0a, 0x26, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x69, 0x6e, 0x73, 0x70, 0x69, 0x72, 0x69,
	0x74, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x75, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x1a, 0x25, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe0, 0x02, 0x0a, 0x10, 0x42, 0x75, 0x64, 0x67,
	0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x4d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x4d, 0x61, 0x78, 0x12, 0x36, 0x0a, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x75, 0x6d,
	0x52, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x75,
	0x64, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x42,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x12, 0x38, 0x0a, 0x0b, 0x42, 0x75, 0x64, 0x67,
	0x65, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x0b, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x95, 0x02, 0x0a, 0x15, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x61, 0x78, 0x12, 0x36, 0x0a, 0x0a,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x69,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x4d,
	0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x78,
	0x12, 0x38, 0x0a, 0x0b, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x0b, 0x42,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65,
	0x6d, 0x61, 0x72, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61,
	0x72, 0x6b, 0x22, 0x55, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67,
	0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0c, 0x42,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65,
	0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x42, 0x75, 0x64,
	0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x22, 0x55, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x4f, 0x6e, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x3c, 0x0a, 0x0c, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0c, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73,
	0x22, 0x55, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0c, 0x42, 0x75, 0x64,
	0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41,
	0x73, 0x73, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x42, 0x75, 0x64, 0x67, 0x65,
	0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x22, 0x7e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x3c, 0x0a, 0x0c, 0x42, 0x75, 0x64,
	0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41,
	0x73, 0x73, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x42, 0x75, 0x64, 0x67, 0x65,
	0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x55, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x3c, 0x0a, 0x0c, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x42,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0c, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x22, 0x45, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x42, 0x75,
	0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x22, 0xa5, 0x02, 0x0a, 0x15, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x42,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1a,
	0x0a, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x4d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x4d, 0x61, 0x78, 0x12, 0x36, 0x0a, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e,
	0x75, 0x6d, 0x52, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x09, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x12, 0x38, 0x0a, 0x0b, 0x42, 0x75,
	0x64, 0x67, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x0b, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x15,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0c, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41,
	0x73, 0x73, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73,
	0x65, 0x73, 0x73, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x64,
	0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x15,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x73, 0x67, 0x32, 0xcd, 0x03, 0x0a, 0x0c, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x12, 0x48, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x48, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41,
	0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x48, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12, 0x1d, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x42, 0x75, 0x64, 0x67, 0x65,
	0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x75, 0x64, 0x67, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6a, 0x31, 0x35, 0x37, 0x30, 0x36, 0x39, 0x33, 0x36, 0x35, 0x39,
	0x2f, 0x67, 0x66, 0x63, 0x71, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2f, 0x69, 0x6e, 0x73, 0x70, 0x69, 0x72, 0x69, 0x74, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_inspirit_v1_budget_access_proto_rawDescOnce sync.Once
	file_config_inspirit_v1_budget_access_proto_rawDescData = file_config_inspirit_v1_budget_access_proto_rawDesc
)

func file_config_inspirit_v1_budget_access_proto_rawDescGZIP() []byte {
	file_config_inspirit_v1_budget_access_proto_rawDescOnce.Do(func() {
		file_config_inspirit_v1_budget_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_inspirit_v1_budget_access_proto_rawDescData)
	})
	return file_config_inspirit_v1_budget_access_proto_rawDescData
}

var file_config_inspirit_v1_budget_access_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_config_inspirit_v1_budget_access_proto_goTypes = []interface{}{
	(*BudgetAssessInfo)(nil),       // 0: config.BudgetAssessInfo
	(*CreateBudgetAssessReq)(nil),  // 1: config.CreateBudgetAssessReq
	(*CreateBudgetAssessRes)(nil),  // 2: config.CreateBudgetAssessRes
	(*GetOneBudgetAssessReq)(nil),  // 3: config.GetOneBudgetAssessReq
	(*GetOneBudgetAssessRes)(nil),  // 4: config.GetOneBudgetAssessRes
	(*GetListBudgetAssessReq)(nil), // 5: config.GetListBudgetAssessReq
	(*GetListBudgetAssessRes)(nil), // 6: config.GetListBudgetAssessRes
	(*GetAllBudgetAssessReq)(nil),  // 7: config.GetAllBudgetAssessReq
	(*GetAllBudgetAssessRes)(nil),  // 8: config.GetAllBudgetAssessRes
	(*ModifyBudgetAssessReq)(nil),  // 9: config.ModifyBudgetAssessReq
	(*ModifyBudgetAssessRes)(nil),  // 10: config.ModifyBudgetAssessRes
	(*DeleteBudgetAssessReq)(nil),  // 11: config.DeleteBudgetAssessReq
	(*DeleteBudgetAssessRes)(nil),  // 12: config.DeleteBudgetAssessRes
	(v1.ScoreRangeEnum)(0),         // 13: config.ScoreRangeEnum
}
var file_config_inspirit_v1_budget_access_proto_depIdxs = []int32{
	13, // 0: config.BudgetAssessInfo.ScoreRange:type_name -> config.ScoreRangeEnum
	13, // 1: config.BudgetAssessInfo.BudgetRange:type_name -> config.ScoreRangeEnum
	13, // 2: config.CreateBudgetAssessReq.ScoreRange:type_name -> config.ScoreRangeEnum
	13, // 3: config.CreateBudgetAssessReq.BudgetRange:type_name -> config.ScoreRangeEnum
	0,  // 4: config.CreateBudgetAssessRes.BudgetAssess:type_name -> config.BudgetAssessInfo
	0,  // 5: config.GetOneBudgetAssessReq.BudgetAssess:type_name -> config.BudgetAssessInfo
	0,  // 6: config.GetOneBudgetAssessRes.BudgetAssess:type_name -> config.BudgetAssessInfo
	0,  // 7: config.GetListBudgetAssessReq.BudgetAssess:type_name -> config.BudgetAssessInfo
	0,  // 8: config.GetListBudgetAssessRes.Data:type_name -> config.BudgetAssessInfo
	0,  // 9: config.GetAllBudgetAssessReq.BudgetAssess:type_name -> config.BudgetAssessInfo
	0,  // 10: config.GetAllBudgetAssessRes.Data:type_name -> config.BudgetAssessInfo
	13, // 11: config.ModifyBudgetAssessReq.ScoreRange:type_name -> config.ScoreRangeEnum
	13, // 12: config.ModifyBudgetAssessReq.BudgetRange:type_name -> config.ScoreRangeEnum
	0,  // 13: config.ModifyBudgetAssessRes.BudgetAssess:type_name -> config.BudgetAssessInfo
	1,  // 14: config.BudgetAssess.Create:input_type -> config.CreateBudgetAssessReq
	3,  // 15: config.BudgetAssess.GetOne:input_type -> config.GetOneBudgetAssessReq
	5,  // 16: config.BudgetAssess.GetList:input_type -> config.GetListBudgetAssessReq
	7,  // 17: config.BudgetAssess.GetAll:input_type -> config.GetAllBudgetAssessReq
	9,  // 18: config.BudgetAssess.Modify:input_type -> config.ModifyBudgetAssessReq
	11, // 19: config.BudgetAssess.Delete:input_type -> config.DeleteBudgetAssessReq
	2,  // 20: config.BudgetAssess.Create:output_type -> config.CreateBudgetAssessRes
	4,  // 21: config.BudgetAssess.GetOne:output_type -> config.GetOneBudgetAssessRes
	6,  // 22: config.BudgetAssess.GetList:output_type -> config.GetListBudgetAssessRes
	8,  // 23: config.BudgetAssess.GetAll:output_type -> config.GetAllBudgetAssessRes
	10, // 24: config.BudgetAssess.Modify:output_type -> config.ModifyBudgetAssessRes
	12, // 25: config.BudgetAssess.Delete:output_type -> config.DeleteBudgetAssessRes
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_config_inspirit_v1_budget_access_proto_init() }
func file_config_inspirit_v1_budget_access_proto_init() {
	if File_config_inspirit_v1_budget_access_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_inspirit_v1_budget_access_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BudgetAssessInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBudgetAssessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBudgetAssessRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneBudgetAssessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOneBudgetAssessRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListBudgetAssessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListBudgetAssessRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBudgetAssessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBudgetAssessRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyBudgetAssessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyBudgetAssessRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBudgetAssessReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_budget_access_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBudgetAssessRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_inspirit_v1_budget_access_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_inspirit_v1_budget_access_proto_goTypes,
		DependencyIndexes: file_config_inspirit_v1_budget_access_proto_depIdxs,
		MessageInfos:      file_config_inspirit_v1_budget_access_proto_msgTypes,
	}.Build()
	File_config_inspirit_v1_budget_access_proto = out.File
	file_config_inspirit_v1_budget_access_proto_rawDesc = nil
	file_config_inspirit_v1_budget_access_proto_goTypes = nil
	file_config_inspirit_v1_budget_access_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BudgetAssessClient is the client API for BudgetAssess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BudgetAssessClient interface {
	Create(ctx context.Context, in *CreateBudgetAssessReq, opts ...grpc.CallOption) (*CreateBudgetAssessRes, error)
	GetOne(ctx context.Context, in *GetOneBudgetAssessReq, opts ...grpc.CallOption) (*GetOneBudgetAssessRes, error)
	GetList(ctx context.Context, in *GetListBudgetAssessReq, opts ...grpc.CallOption) (*GetListBudgetAssessRes, error)
	GetAll(ctx context.Context, in *GetAllBudgetAssessReq, opts ...grpc.CallOption) (*GetAllBudgetAssessRes, error)
	Modify(ctx context.Context, in *ModifyBudgetAssessReq, opts ...grpc.CallOption) (*ModifyBudgetAssessRes, error)
	Delete(ctx context.Context, in *DeleteBudgetAssessReq, opts ...grpc.CallOption) (*DeleteBudgetAssessRes, error)
}

type budgetAssessClient struct {
	cc grpc.ClientConnInterface
}

func NewBudgetAssessClient(cc grpc.ClientConnInterface) BudgetAssessClient {
	return &budgetAssessClient{cc}
}

func (c *budgetAssessClient) Create(ctx context.Context, in *CreateBudgetAssessReq, opts ...grpc.CallOption) (*CreateBudgetAssessRes, error) {
	out := new(CreateBudgetAssessRes)
	err := c.cc.Invoke(ctx, "/config.BudgetAssess/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetAssessClient) GetOne(ctx context.Context, in *GetOneBudgetAssessReq, opts ...grpc.CallOption) (*GetOneBudgetAssessRes, error) {
	out := new(GetOneBudgetAssessRes)
	err := c.cc.Invoke(ctx, "/config.BudgetAssess/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetAssessClient) GetList(ctx context.Context, in *GetListBudgetAssessReq, opts ...grpc.CallOption) (*GetListBudgetAssessRes, error) {
	out := new(GetListBudgetAssessRes)
	err := c.cc.Invoke(ctx, "/config.BudgetAssess/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetAssessClient) GetAll(ctx context.Context, in *GetAllBudgetAssessReq, opts ...grpc.CallOption) (*GetAllBudgetAssessRes, error) {
	out := new(GetAllBudgetAssessRes)
	err := c.cc.Invoke(ctx, "/config.BudgetAssess/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetAssessClient) Modify(ctx context.Context, in *ModifyBudgetAssessReq, opts ...grpc.CallOption) (*ModifyBudgetAssessRes, error) {
	out := new(ModifyBudgetAssessRes)
	err := c.cc.Invoke(ctx, "/config.BudgetAssess/Modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *budgetAssessClient) Delete(ctx context.Context, in *DeleteBudgetAssessReq, opts ...grpc.CallOption) (*DeleteBudgetAssessRes, error) {
	out := new(DeleteBudgetAssessRes)
	err := c.cc.Invoke(ctx, "/config.BudgetAssess/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BudgetAssessServer is the server API for BudgetAssess service.
type BudgetAssessServer interface {
	Create(context.Context, *CreateBudgetAssessReq) (*CreateBudgetAssessRes, error)
	GetOne(context.Context, *GetOneBudgetAssessReq) (*GetOneBudgetAssessRes, error)
	GetList(context.Context, *GetListBudgetAssessReq) (*GetListBudgetAssessRes, error)
	GetAll(context.Context, *GetAllBudgetAssessReq) (*GetAllBudgetAssessRes, error)
	Modify(context.Context, *ModifyBudgetAssessReq) (*ModifyBudgetAssessRes, error)
	Delete(context.Context, *DeleteBudgetAssessReq) (*DeleteBudgetAssessRes, error)
}

// UnimplementedBudgetAssessServer can be embedded to have forward compatible implementations.
type UnimplementedBudgetAssessServer struct {
}

func (*UnimplementedBudgetAssessServer) Create(context.Context, *CreateBudgetAssessReq) (*CreateBudgetAssessRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBudgetAssessServer) GetOne(context.Context, *GetOneBudgetAssessReq) (*GetOneBudgetAssessRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (*UnimplementedBudgetAssessServer) GetList(context.Context, *GetListBudgetAssessReq) (*GetListBudgetAssessRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedBudgetAssessServer) GetAll(context.Context, *GetAllBudgetAssessReq) (*GetAllBudgetAssessRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedBudgetAssessServer) Modify(context.Context, *ModifyBudgetAssessReq) (*ModifyBudgetAssessRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (*UnimplementedBudgetAssessServer) Delete(context.Context, *DeleteBudgetAssessReq) (*DeleteBudgetAssessRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterBudgetAssessServer(s *grpc.Server, srv BudgetAssessServer) {
	s.RegisterService(&_BudgetAssess_serviceDesc, srv)
}

func _BudgetAssess_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBudgetAssessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetAssessServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.BudgetAssess/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetAssessServer).Create(ctx, req.(*CreateBudgetAssessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetAssess_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneBudgetAssessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetAssessServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.BudgetAssess/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetAssessServer).GetOne(ctx, req.(*GetOneBudgetAssessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetAssess_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListBudgetAssessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetAssessServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.BudgetAssess/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetAssessServer).GetList(ctx, req.(*GetListBudgetAssessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetAssess_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllBudgetAssessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetAssessServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.BudgetAssess/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetAssessServer).GetAll(ctx, req.(*GetAllBudgetAssessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetAssess_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyBudgetAssessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetAssessServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.BudgetAssess/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetAssessServer).Modify(ctx, req.(*ModifyBudgetAssessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BudgetAssess_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBudgetAssessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetAssessServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.BudgetAssess/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetAssessServer).Delete(ctx, req.(*DeleteBudgetAssessReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BudgetAssess_serviceDesc = grpc.ServiceDesc{
	ServiceName: "config.BudgetAssess",
	HandlerType: (*BudgetAssessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BudgetAssess_Create_Handler,
		},
		{
			MethodName: "GetOne",
			Handler:    _BudgetAssess_GetOne_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _BudgetAssess_GetList_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _BudgetAssess_GetAll_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _BudgetAssess_Modify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BudgetAssess_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config/inspirit/v1/budget_access.proto",
}
