// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.3
// source: config/inspirit/v1/pm_hours_index.proto

package v1

import (
	context "context"
	reflect "reflect"
	sync "sync"

	v1 "github.com/lj1570693659/gfcq_protoc/config/product/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PmPmHoursIndex is the golang structure for table Pm_hours_index.
type PmHoursIndexInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32             `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	ScoreIndex uint32            `protobuf:"varint,2,opt,name=ScoreIndex,proto3" json:"ScoreIndex"`                            // 工时指数
	ScoreMin   float32           `protobuf:"fixed32,3,opt,name=ScoreMin,proto3" json:"ScoreMin"`                               // 分值下限
	ScoreMax   float32           `protobuf:"fixed32,4,opt,name=ScoreMax,proto3" json:"ScoreMax"`                               // 分值上限
	ScoreRange v1.ScoreRangeEnum `protobuf:"varint,5,opt,name=ScoreRange,proto3,enum=config.ScoreRangeEnum" json:"ScoreRange"` // 分数区间包含关系（1：左闭右开，2：左开右闭）
	Remark     string            `protobuf:"bytes,6,opt,name=Remark,proto3" json:"Remark"`                                     // 预留备注说明信息
	CreateTime string            `protobuf:"bytes,7,opt,name=CreateTime,proto3" json:"CreateTime"`                             // 数据新增时间
	UpdateTime string            `protobuf:"bytes,8,opt,name=UpdateTime,proto3" json:"UpdateTime"`                             // 最后一次更新数据时间
}

func (x *PmHoursIndexInfo) Reset() {
	*x = PmHoursIndexInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PmHoursIndexInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PmHoursIndexInfo) ProtoMessage() {}

func (x *PmHoursIndexInfo) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PmHoursIndexInfo.ProtoReflect.Descriptor instead.
func (*PmHoursIndexInfo) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP(), []int{0}
}

func (x *PmHoursIndexInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PmHoursIndexInfo) GetScoreIndex() uint32 {
	if x != nil {
		return x.ScoreIndex
	}
	return 0
}

func (x *PmHoursIndexInfo) GetScoreMin() float32 {
	if x != nil {
		return x.ScoreMin
	}
	return 0
}

func (x *PmHoursIndexInfo) GetScoreMax() float32 {
	if x != nil {
		return x.ScoreMax
	}
	return 0
}

func (x *PmHoursIndexInfo) GetScoreRange() v1.ScoreRangeEnum {
	if x != nil {
		return x.ScoreRange
	}
	return v1.ScoreRangeEnum(0)
}

func (x *PmHoursIndexInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *PmHoursIndexInfo) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *PmHoursIndexInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

// 创建数据接口输入数据结构
type CreatePmHoursIndexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remark     string            `protobuf:"bytes,1,opt,name=Remark,proto3" json:"Remark"`
	ScoreIndex uint32            `protobuf:"varint,2,opt,name=ScoreIndex,proto3" json:"ScoreIndex"`                            // 工时指数
	ScoreMin   float32           `protobuf:"fixed32,3,opt,name=ScoreMin,proto3" json:"ScoreMin"`                               // 分值下限
	ScoreMax   float32           `protobuf:"fixed32,4,opt,name=ScoreMax,proto3" json:"ScoreMax"`                               // 分值上限
	ScoreRange v1.ScoreRangeEnum `protobuf:"varint,5,opt,name=ScoreRange,proto3,enum=config.ScoreRangeEnum" json:"ScoreRange"` // 分数区间包含关系（1：左闭右开，2：左开右闭）
}

func (x *CreatePmHoursIndexReq) Reset() {
	*x = CreatePmHoursIndexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePmHoursIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePmHoursIndexReq) ProtoMessage() {}

func (x *CreatePmHoursIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePmHoursIndexReq.ProtoReflect.Descriptor instead.
func (*CreatePmHoursIndexReq) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePmHoursIndexReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CreatePmHoursIndexReq) GetScoreIndex() uint32 {
	if x != nil {
		return x.ScoreIndex
	}
	return 0
}

func (x *CreatePmHoursIndexReq) GetScoreMin() float32 {
	if x != nil {
		return x.ScoreMin
	}
	return 0
}

func (x *CreatePmHoursIndexReq) GetScoreMax() float32 {
	if x != nil {
		return x.ScoreMax
	}
	return 0
}

func (x *CreatePmHoursIndexReq) GetScoreRange() v1.ScoreRangeEnum {
	if x != nil {
		return x.ScoreRange
	}
	return v1.ScoreRangeEnum(0)
}

// 创建数据接口输出数据结构
type CreatePmHoursIndexRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PmHoursIndex *PmHoursIndexInfo `protobuf:"bytes,1,opt,name=PmHoursIndex,proto3" json:"PmHoursIndex"`
}

func (x *CreatePmHoursIndexRes) Reset() {
	*x = CreatePmHoursIndexRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePmHoursIndexRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePmHoursIndexRes) ProtoMessage() {}

func (x *CreatePmHoursIndexRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePmHoursIndexRes.ProtoReflect.Descriptor instead.
func (*CreatePmHoursIndexRes) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePmHoursIndexRes) GetPmHoursIndex() *PmHoursIndexInfo {
	if x != nil {
		return x.PmHoursIndex
	}
	return nil
}

// 获取详情接口输入数据结构
type GetOnePmHoursIndexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PmHoursIndex *PmHoursIndexInfo `protobuf:"bytes,1,opt,name=PmHoursIndex,proto3" json:"PmHoursIndex"`
}

func (x *GetOnePmHoursIndexReq) Reset() {
	*x = GetOnePmHoursIndexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOnePmHoursIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnePmHoursIndexReq) ProtoMessage() {}

func (x *GetOnePmHoursIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnePmHoursIndexReq.ProtoReflect.Descriptor instead.
func (*GetOnePmHoursIndexReq) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP(), []int{3}
}

func (x *GetOnePmHoursIndexReq) GetPmHoursIndex() *PmHoursIndexInfo {
	if x != nil {
		return x.PmHoursIndex
	}
	return nil
}

// 获取详情接口输出数据结构
type GetOnePmHoursIndexRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PmHoursIndex *PmHoursIndexInfo `protobuf:"bytes,1,opt,name=PmHoursIndex,proto3" json:"PmHoursIndex"`
}

func (x *GetOnePmHoursIndexRes) Reset() {
	*x = GetOnePmHoursIndexRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOnePmHoursIndexRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnePmHoursIndexRes) ProtoMessage() {}

func (x *GetOnePmHoursIndexRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnePmHoursIndexRes.ProtoReflect.Descriptor instead.
func (*GetOnePmHoursIndexRes) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP(), []int{4}
}

func (x *GetOnePmHoursIndexRes) GetPmHoursIndex() *PmHoursIndexInfo {
	if x != nil {
		return x.PmHoursIndex
	}
	return nil
}

// 列表接口输入数据结构
type GetListPmHoursIndexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page         int32             `protobuf:"varint,1,opt,name=Page,proto3" json:"Page"`
	Size         int32             `protobuf:"varint,2,opt,name=Size,proto3" json:"Size"`
	PmHoursIndex *PmHoursIndexInfo `protobuf:"bytes,3,opt,name=PmHoursIndex,proto3" json:"PmHoursIndex"`
}

func (x *GetListPmHoursIndexReq) Reset() {
	*x = GetListPmHoursIndexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListPmHoursIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPmHoursIndexReq) ProtoMessage() {}

func (x *GetListPmHoursIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPmHoursIndexReq.ProtoReflect.Descriptor instead.
func (*GetListPmHoursIndexReq) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP(), []int{5}
}

func (x *GetListPmHoursIndexReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListPmHoursIndexReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListPmHoursIndexReq) GetPmHoursIndex() *PmHoursIndexInfo {
	if x != nil {
		return x.PmHoursIndex
	}
	return nil
}

// 列表接口输出数据结构
type GetListPmHoursIndexRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      int32               `protobuf:"varint,1,opt,name=Page,proto3" json:"Page"`
	Size      int32               `protobuf:"varint,2,opt,name=Size,proto3" json:"Size"`
	TotalSize int32               `protobuf:"varint,3,opt,name=TotalSize,proto3" json:"TotalSize"`
	Data      []*PmHoursIndexInfo `protobuf:"bytes,4,rep,name=Data,proto3" json:"Data"`
}

func (x *GetListPmHoursIndexRes) Reset() {
	*x = GetListPmHoursIndexRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListPmHoursIndexRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListPmHoursIndexRes) ProtoMessage() {}

func (x *GetListPmHoursIndexRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListPmHoursIndexRes.ProtoReflect.Descriptor instead.
func (*GetListPmHoursIndexRes) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP(), []int{6}
}

func (x *GetListPmHoursIndexRes) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetListPmHoursIndexRes) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetListPmHoursIndexRes) GetTotalSize() int32 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *GetListPmHoursIndexRes) GetData() []*PmHoursIndexInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

// 修改数据接口输入数据结构
type ModifyPmHoursIndexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Remark     string            `protobuf:"bytes,1,opt,name=Remark,proto3" json:"Remark"`
	ScoreIndex uint32            `protobuf:"varint,2,opt,name=ScoreIndex,proto3" json:"ScoreIndex"`                            // 工时指数
	ScoreMin   float32           `protobuf:"fixed32,3,opt,name=ScoreMin,proto3" json:"ScoreMin"`                               // 分值下限
	ScoreMax   float32           `protobuf:"fixed32,4,opt,name=ScoreMax,proto3" json:"ScoreMax"`                               // 分值上限
	ScoreRange v1.ScoreRangeEnum `protobuf:"varint,5,opt,name=ScoreRange,proto3,enum=config.ScoreRangeEnum" json:"ScoreRange"` // 分数区间包含关系（1：左闭右开，2：左开右闭）
	Id         int32             `protobuf:"varint,6,opt,name=Id,proto3" json:"Id"`                                            // v: required
}

func (x *ModifyPmHoursIndexReq) Reset() {
	*x = ModifyPmHoursIndexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyPmHoursIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPmHoursIndexReq) ProtoMessage() {}

func (x *ModifyPmHoursIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPmHoursIndexReq.ProtoReflect.Descriptor instead.
func (*ModifyPmHoursIndexReq) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP(), []int{7}
}

func (x *ModifyPmHoursIndexReq) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *ModifyPmHoursIndexReq) GetScoreIndex() uint32 {
	if x != nil {
		return x.ScoreIndex
	}
	return 0
}

func (x *ModifyPmHoursIndexReq) GetScoreMin() float32 {
	if x != nil {
		return x.ScoreMin
	}
	return 0
}

func (x *ModifyPmHoursIndexReq) GetScoreMax() float32 {
	if x != nil {
		return x.ScoreMax
	}
	return 0
}

func (x *ModifyPmHoursIndexReq) GetScoreRange() v1.ScoreRangeEnum {
	if x != nil {
		return x.ScoreRange
	}
	return v1.ScoreRangeEnum(0)
}

func (x *ModifyPmHoursIndexReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 修改数据接口输出数据结构
type ModifyPmHoursIndexRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PmHoursIndex *PmHoursIndexInfo `protobuf:"bytes,3,opt,name=PmHoursIndex,proto3" json:"PmHoursIndex"`
}

func (x *ModifyPmHoursIndexRes) Reset() {
	*x = ModifyPmHoursIndexRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyPmHoursIndexRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyPmHoursIndexRes) ProtoMessage() {}

func (x *ModifyPmHoursIndexRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyPmHoursIndexRes.ProtoReflect.Descriptor instead.
func (*ModifyPmHoursIndexRes) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP(), []int{8}
}

func (x *ModifyPmHoursIndexRes) GetPmHoursIndex() *PmHoursIndexInfo {
	if x != nil {
		return x.PmHoursIndex
	}
	return nil
}

// 删除数据接口输入数据结构
type DeletePmHoursIndexReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"` // v: required
}

func (x *DeletePmHoursIndexReq) Reset() {
	*x = DeletePmHoursIndexReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePmHoursIndexReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePmHoursIndexReq) ProtoMessage() {}

func (x *DeletePmHoursIndexReq) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePmHoursIndexReq.ProtoReflect.Descriptor instead.
func (*DeletePmHoursIndexReq) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePmHoursIndexReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除数据接口输出数据结构
type DeletePmHoursIndexRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool   `protobuf:"varint,1,opt,name=IsSuccess,proto3" json:"IsSuccess"` // v: required
	Msg       string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg"`              // v: required
}

func (x *DeletePmHoursIndexRes) Reset() {
	*x = DeletePmHoursIndexRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePmHoursIndexRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePmHoursIndexRes) ProtoMessage() {}

func (x *DeletePmHoursIndexRes) ProtoReflect() protoreflect.Message {
	mi := &file_config_inspirit_v1_pm_hours_index_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePmHoursIndexRes.ProtoReflect.Descriptor instead.
func (*DeletePmHoursIndexRes) Descriptor() ([]byte, []int) {
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePmHoursIndexRes) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *DeletePmHoursIndexRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_config_inspirit_v1_pm_hours_index_proto protoreflect.FileDescriptor

var file_config_inspirit_v1_pm_hours_index_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x69, 0x6e, 0x73, 0x70, 0x69, 0x72, 0x69,
	0x74, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6d, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x1a, 0x25, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x02, 0x0a, 0x10, 0x50, 0x6d, 0x48,
	0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x4d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x4d, 0x61, 0x78, 0x12, 0x36, 0x0a, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52,
	0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xbf, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x4d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x4d, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x61, 0x78, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x61, 0x78, 0x12,
	0x36, 0x0a, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x0a, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73,
	0x12, 0x3c, 0x0a, 0x0c, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0c, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x55,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x12, 0x3c, 0x0a, 0x0c, 0x50, 0x6d, 0x48, 0x6f, 0x75,
	0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x55, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x50,
	0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x12, 0x3c,
	0x0a, 0x0c, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6d,
	0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c,
	0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x7e, 0x0a, 0x16,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x3c,
	0x0a, 0x0c, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6d,
	0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c,
	0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x8c, 0x01, 0x0a,
	0x16, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2c, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0xcf, 0x01, 0x0a, 0x15,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1e, 0x0a,
	0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x08, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4d, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x4d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x4d, 0x61, 0x78, 0x12, 0x36, 0x0a, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x0a, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x55, 0x0a,
	0x15, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0c, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72,
	0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6d,
	0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x22, 0x47, 0x0a,
	0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x32, 0x83, 0x03, 0x0a, 0x0c, 0x50, 0x6d, 0x48, 0x6f, 0x75,
	0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x48, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71,
	0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x48, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x12, 0x1d, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x50, 0x6d, 0x48, 0x6f, 0x75,
	0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x6e, 0x65, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72,
	0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65,
	0x71, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x50, 0x6d, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x48, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6d, 0x48, 0x6f,
	0x75, 0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6d, 0x48, 0x6f, 0x75,
	0x72, 0x73, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6a, 0x31, 0x35, 0x37,
	0x30, 0x36, 0x39, 0x33, 0x36, 0x35, 0x39, 0x2f, 0x67, 0x66, 0x63, 0x71, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x69, 0x6e, 0x73, 0x70, 0x69,
	0x72, 0x69, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_config_inspirit_v1_pm_hours_index_proto_rawDescOnce sync.Once
	file_config_inspirit_v1_pm_hours_index_proto_rawDescData = file_config_inspirit_v1_pm_hours_index_proto_rawDesc
)

func file_config_inspirit_v1_pm_hours_index_proto_rawDescGZIP() []byte {
	file_config_inspirit_v1_pm_hours_index_proto_rawDescOnce.Do(func() {
		file_config_inspirit_v1_pm_hours_index_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_inspirit_v1_pm_hours_index_proto_rawDescData)
	})
	return file_config_inspirit_v1_pm_hours_index_proto_rawDescData
}

var file_config_inspirit_v1_pm_hours_index_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_config_inspirit_v1_pm_hours_index_proto_goTypes = []interface{}{
	(*PmHoursIndexInfo)(nil),       // 0: config.PmHoursIndexInfo
	(*CreatePmHoursIndexReq)(nil),  // 1: config.CreatePmHoursIndexReq
	(*CreatePmHoursIndexRes)(nil),  // 2: config.CreatePmHoursIndexRes
	(*GetOnePmHoursIndexReq)(nil),  // 3: config.GetOnePmHoursIndexReq
	(*GetOnePmHoursIndexRes)(nil),  // 4: config.GetOnePmHoursIndexRes
	(*GetListPmHoursIndexReq)(nil), // 5: config.GetListPmHoursIndexReq
	(*GetListPmHoursIndexRes)(nil), // 6: config.GetListPmHoursIndexRes
	(*ModifyPmHoursIndexReq)(nil),  // 7: config.ModifyPmHoursIndexReq
	(*ModifyPmHoursIndexRes)(nil),  // 8: config.ModifyPmHoursIndexRes
	(*DeletePmHoursIndexReq)(nil),  // 9: config.DeletePmHoursIndexReq
	(*DeletePmHoursIndexRes)(nil),  // 10: config.DeletePmHoursIndexRes
	(v1.ScoreRangeEnum)(0),         // 11: config.ScoreRangeEnum
}
var file_config_inspirit_v1_pm_hours_index_proto_depIdxs = []int32{
	11, // 0: config.PmHoursIndexInfo.ScoreRange:type_name -> config.ScoreRangeEnum
	11, // 1: config.CreatePmHoursIndexReq.ScoreRange:type_name -> config.ScoreRangeEnum
	0,  // 2: config.CreatePmHoursIndexRes.PmHoursIndex:type_name -> config.PmHoursIndexInfo
	0,  // 3: config.GetOnePmHoursIndexReq.PmHoursIndex:type_name -> config.PmHoursIndexInfo
	0,  // 4: config.GetOnePmHoursIndexRes.PmHoursIndex:type_name -> config.PmHoursIndexInfo
	0,  // 5: config.GetListPmHoursIndexReq.PmHoursIndex:type_name -> config.PmHoursIndexInfo
	0,  // 6: config.GetListPmHoursIndexRes.Data:type_name -> config.PmHoursIndexInfo
	11, // 7: config.ModifyPmHoursIndexReq.ScoreRange:type_name -> config.ScoreRangeEnum
	0,  // 8: config.ModifyPmHoursIndexRes.PmHoursIndex:type_name -> config.PmHoursIndexInfo
	1,  // 9: config.PmHoursIndex.Create:input_type -> config.CreatePmHoursIndexReq
	3,  // 10: config.PmHoursIndex.GetOne:input_type -> config.GetOnePmHoursIndexReq
	5,  // 11: config.PmHoursIndex.GetList:input_type -> config.GetListPmHoursIndexReq
	7,  // 12: config.PmHoursIndex.Modify:input_type -> config.ModifyPmHoursIndexReq
	9,  // 13: config.PmHoursIndex.Delete:input_type -> config.DeletePmHoursIndexReq
	2,  // 14: config.PmHoursIndex.Create:output_type -> config.CreatePmHoursIndexRes
	4,  // 15: config.PmHoursIndex.GetOne:output_type -> config.GetOnePmHoursIndexRes
	6,  // 16: config.PmHoursIndex.GetList:output_type -> config.GetListPmHoursIndexRes
	8,  // 17: config.PmHoursIndex.Modify:output_type -> config.ModifyPmHoursIndexRes
	10, // 18: config.PmHoursIndex.Delete:output_type -> config.DeletePmHoursIndexRes
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_config_inspirit_v1_pm_hours_index_proto_init() }
func file_config_inspirit_v1_pm_hours_index_proto_init() {
	if File_config_inspirit_v1_pm_hours_index_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_inspirit_v1_pm_hours_index_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PmHoursIndexInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_pm_hours_index_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePmHoursIndexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_pm_hours_index_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePmHoursIndexRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_pm_hours_index_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOnePmHoursIndexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_pm_hours_index_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOnePmHoursIndexRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_pm_hours_index_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListPmHoursIndexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_pm_hours_index_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListPmHoursIndexRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_pm_hours_index_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyPmHoursIndexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_pm_hours_index_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyPmHoursIndexRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_pm_hours_index_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePmHoursIndexReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_inspirit_v1_pm_hours_index_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePmHoursIndexRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_inspirit_v1_pm_hours_index_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_inspirit_v1_pm_hours_index_proto_goTypes,
		DependencyIndexes: file_config_inspirit_v1_pm_hours_index_proto_depIdxs,
		MessageInfos:      file_config_inspirit_v1_pm_hours_index_proto_msgTypes,
	}.Build()
	File_config_inspirit_v1_pm_hours_index_proto = out.File
	file_config_inspirit_v1_pm_hours_index_proto_rawDesc = nil
	file_config_inspirit_v1_pm_hours_index_proto_goTypes = nil
	file_config_inspirit_v1_pm_hours_index_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PmHoursIndexClient is the client API for PmHoursIndex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PmHoursIndexClient interface {
	Create(ctx context.Context, in *CreatePmHoursIndexReq, opts ...grpc.CallOption) (*CreatePmHoursIndexRes, error)
	GetOne(ctx context.Context, in *GetOnePmHoursIndexReq, opts ...grpc.CallOption) (*GetOnePmHoursIndexRes, error)
	GetList(ctx context.Context, in *GetListPmHoursIndexReq, opts ...grpc.CallOption) (*GetListPmHoursIndexRes, error)
	Modify(ctx context.Context, in *ModifyPmHoursIndexReq, opts ...grpc.CallOption) (*ModifyPmHoursIndexRes, error)
	Delete(ctx context.Context, in *DeletePmHoursIndexReq, opts ...grpc.CallOption) (*DeletePmHoursIndexRes, error)
}

type pmHoursIndexClient struct {
	cc grpc.ClientConnInterface
}

func NewPmHoursIndexClient(cc grpc.ClientConnInterface) PmHoursIndexClient {
	return &pmHoursIndexClient{cc}
}

func (c *pmHoursIndexClient) Create(ctx context.Context, in *CreatePmHoursIndexReq, opts ...grpc.CallOption) (*CreatePmHoursIndexRes, error) {
	out := new(CreatePmHoursIndexRes)
	err := c.cc.Invoke(ctx, "/config.PmHoursIndex/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmHoursIndexClient) GetOne(ctx context.Context, in *GetOnePmHoursIndexReq, opts ...grpc.CallOption) (*GetOnePmHoursIndexRes, error) {
	out := new(GetOnePmHoursIndexRes)
	err := c.cc.Invoke(ctx, "/config.PmHoursIndex/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmHoursIndexClient) GetList(ctx context.Context, in *GetListPmHoursIndexReq, opts ...grpc.CallOption) (*GetListPmHoursIndexRes, error) {
	out := new(GetListPmHoursIndexRes)
	err := c.cc.Invoke(ctx, "/config.PmHoursIndex/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmHoursIndexClient) Modify(ctx context.Context, in *ModifyPmHoursIndexReq, opts ...grpc.CallOption) (*ModifyPmHoursIndexRes, error) {
	out := new(ModifyPmHoursIndexRes)
	err := c.cc.Invoke(ctx, "/config.PmHoursIndex/Modify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pmHoursIndexClient) Delete(ctx context.Context, in *DeletePmHoursIndexReq, opts ...grpc.CallOption) (*DeletePmHoursIndexRes, error) {
	out := new(DeletePmHoursIndexRes)
	err := c.cc.Invoke(ctx, "/config.PmHoursIndex/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PmHoursIndexServer is the server API for PmHoursIndex service.
type PmHoursIndexServer interface {
	Create(context.Context, *CreatePmHoursIndexReq) (*CreatePmHoursIndexRes, error)
	GetOne(context.Context, *GetOnePmHoursIndexReq) (*GetOnePmHoursIndexRes, error)
	GetList(context.Context, *GetListPmHoursIndexReq) (*GetListPmHoursIndexRes, error)
	Modify(context.Context, *ModifyPmHoursIndexReq) (*ModifyPmHoursIndexRes, error)
	Delete(context.Context, *DeletePmHoursIndexReq) (*DeletePmHoursIndexRes, error)
}

// UnimplementedPmHoursIndexServer can be embedded to have forward compatible implementations.
type UnimplementedPmHoursIndexServer struct {
}

func (*UnimplementedPmHoursIndexServer) Create(context.Context, *CreatePmHoursIndexReq) (*CreatePmHoursIndexRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedPmHoursIndexServer) GetOne(context.Context, *GetOnePmHoursIndexReq) (*GetOnePmHoursIndexRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (*UnimplementedPmHoursIndexServer) GetList(context.Context, *GetListPmHoursIndexReq) (*GetListPmHoursIndexRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (*UnimplementedPmHoursIndexServer) Modify(context.Context, *ModifyPmHoursIndexReq) (*ModifyPmHoursIndexRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Modify not implemented")
}
func (*UnimplementedPmHoursIndexServer) Delete(context.Context, *DeletePmHoursIndexReq) (*DeletePmHoursIndexRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterPmHoursIndexServer(s *grpc.Server, srv PmHoursIndexServer) {
	s.RegisterService(&_PmHoursIndex_serviceDesc, srv)
}

func _PmHoursIndex_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePmHoursIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmHoursIndexServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.PmHoursIndex/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmHoursIndexServer).Create(ctx, req.(*CreatePmHoursIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PmHoursIndex_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnePmHoursIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmHoursIndexServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.PmHoursIndex/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmHoursIndexServer).GetOne(ctx, req.(*GetOnePmHoursIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PmHoursIndex_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListPmHoursIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmHoursIndexServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.PmHoursIndex/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmHoursIndexServer).GetList(ctx, req.(*GetListPmHoursIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PmHoursIndex_Modify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyPmHoursIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmHoursIndexServer).Modify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.PmHoursIndex/Modify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmHoursIndexServer).Modify(ctx, req.(*ModifyPmHoursIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PmHoursIndex_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePmHoursIndexReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PmHoursIndexServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.PmHoursIndex/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PmHoursIndexServer).Delete(ctx, req.(*DeletePmHoursIndexReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PmHoursIndex_serviceDesc = grpc.ServiceDesc{
	ServiceName: "config.PmHoursIndex",
	HandlerType: (*PmHoursIndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PmHoursIndex_Create_Handler,
		},
		{
			MethodName: "GetOne",
			Handler:    _PmHoursIndex_GetOne_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _PmHoursIndex_GetList_Handler,
		},
		{
			MethodName: "Modify",
			Handler:    _PmHoursIndex_Modify_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PmHoursIndex_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config/inspirit/v1/pm_hours_index.proto",
}
